Support websocket reconnect on web3-providers-ws.
ethereum/web3.js pull request #1851
Opened 2018-08-07 16:31 UTC by nujabes403

## Description

Support websocket reconnect, when connection is closed.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran ```npm run test``` with success and extended the tests if necessary.
- [ ] I ran ```npm run build``` and tested the resulting file from ```dist``` folder in a browser.
- [ ] I have tested my code on the live network.

#fix #1558

2018-08-07 16:42 UTC, nujabes403 commented
Please check my request @frozeman @nivida 🙂

2018-08-08 10:01 UTC, levino requested changes
I do not think that this code works. Adding a test that shows that it works would help me in my confidence. Also I think https://github.com/ethereum/web3.js/issues/1852 is not an issue that should be accepted. It is okay to throw an error when the websocket connection fails and let the user handle the problem upstream (by recreating the provider for example)

2018-08-08 10:01 UTC, levino commented on packages/web3-providers-ws/src/index.js
> +    this.reconnect = () => new Ws(url, protocol, undefined, headers);
I would think you must bind the result of `this.reconnect()` to `this.connection`. If not then you are awkwardly relying on some side-effect from the Websockets constructor call. My bet is: This does not work at all. Have you tested it?

My suggestion: Add an automated test for this.

2018-08-08 10:01 UTC, levino commented on packages/web3-providers-ws/src/index.js
> +        callback(new Error('connection not open. try reconnecting...'));
What is the point of throwing an error when at the same trying to solve it. You should silently retry until you are sure there is no way to recover. Then you should stop trying to reconnect and throw an error. This here does not make sense.

2018-08-08 10:21 UTC, frozeman commented on packages/web3-providers-ws/src/index.js
> +    this.reconnect = () => new Ws(url, protocol, undefined, headers);
I agree

2018-08-08 11:39 UTC, nujabes403 commented on packages/web3-providers-ws/src/index.js
> +    this.reconnect = () => new Ws(url, protocol, undefined, headers);
Yes `binding` will be good. Thanks :)

2018-08-08 11:39 UTC, nujabes403 commented on packages/web3-providers-ws/src/index.js
> +        callback(new Error('connection not open. try reconnecting...'));
I agree

2018-08-10 09:28 UTC, frozeman commented on packages/web3-providers-ws/src/index.js
> +        callback(new Error('connection not open. try reconnecting...'));
There is a need to inform web3.js and the developer, as subscription are socket bound, if the socket breaks and auto-reconnects, developers will wonder why they never get their subscriptions again, as it was basically canceled without them knowing. Also web3.js has some logic of re-subscribing. Please check if that still works! https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-subscriptions/src/subscription.js#L278-L289

2018-08-10 10:14 UTC, nujabes403 commented on packages/web3-providers-ws/src/index.js
> +        callback(new Error('connection not open. try reconnecting...'));
@frozeman Thanks! I'll check it :)

2018-11-28 08:50 UTC, nivida commented
I've closed this PR because of #1966

2018-11-28 08:50 UTC, closed without merging