Web3-eth-abi types
ethereum/web3.js pull request #2096
Opened 2018-12-04 18:56 UTC by joshstevens19

As discussed i am building the types for each package. 

Here is the web3-eth-abi types 👍

2018-12-04 20:15 UTC, nivida requested changes

2018-12-04 20:15 UTC, nivida commented on packages/web3-eth-abi/types/tsconfig.json
> +}
Missing EOF :-)

2018-12-04 20:15 UTC, nivida commented on packages/web3-eth-abi/types/tslint.json
> +}
Missing EOF

2018-12-04 22:05 UTC, joshstevens19 commented
all done 👍 @nivida

2018-12-06 11:04 UTC, nivida approved these changes

2018-12-06 11:04 UTC, merged