Web3 provider types
ethereum/web3.js pull request #2112
Opened 2018-12-09 12:15 UTC by joshstevens19

`web3-providers` types written with full tests.

2018-12-10 23:41 UTC, nivida requested changes

2018-12-10 23:41 UTC, nivida commented on packages/web3-providers/types/index.d.ts
> +    send(payload: any, callback: () => void): void;
you could type the payload argument with the JSON-RPC v2 spec if you like.

2018-12-10 23:41 UTC, nivida commented on packages/web3-providers/types/index.d.ts
> +export type provider = HttpProvider | IpcProvider | WebsocketProvider;
provider could also be of type string

2018-12-10 23:41 UTC, nivida commented on packages/web3-providers/types/tests/http-provider-adapter-test.ts
> +// $ExpectType HttpProviderAdapter
add a break above

2018-12-11 09:06 UTC, joshstevens19 commented
@nivida perfect feedback thanks - all ready to be merged now

2018-12-11 09:15 UTC, joshstevens19 commented
@nivida perfect feedback thanks - can you check again and if happy merge it

2018-12-11 11:06 UTC, merged