[WIP] Web3 Module API Documentation
ethereum/web3.js pull request #2236
Opened 2019-01-27 19:41 UTC by nivida

## Description

Adding of a detailed Web3 Module API Documentation.

## Type of change

- [x] Documentation

2019-01-28 08:59 UTC, Levino commented
Hm..

2019-01-28 09:01 UTC, nivida commented
@Levino If you find the time could you please check this documenation if it's understandable or not?

2019-01-28 11:12 UTC, Levino commented
First feedback: I would create an issue for this and reference here with "Fixes #1928282828".
Please update with base branch.

I will continue to review.

2019-01-28 11:15 UTC, Levino commented
- Build does not pass.
- Why is there no preview link? How are the docs hosted?

2019-01-28 11:19 UTC, Levino commented
There is no documentation on how to build the docs locally. There is no hot watcher is there?

2019-01-28 11:21 UTC, Levino commented
Created https://github.com/ethereum/web3.js/issues/2250

2019-01-28 11:23 UTC, Levino commented
How do you want me to review this? Checkout the branch, run `npm run docs` and then go through the PDFs? If https://github.com/ethereum/web3.js/issues/2251 was implemented this would be much nicer.

2019-01-28 11:29 UTC, levino commented
I cannot build this locally.

```bash
npm run docs

> web3@1.0.0-beta.38 docs /home/levin/coding/hardfork/web3.js
> cd docs; make html;

sphinx-build -b html -d _build/doctrees   . _build/html
make: sphinx-build: Command not found
Makefile:53: recipe for target 'html' failed
make: *** [html] Error 127
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! web3@1.0.0-beta.38 docs: `cd docs; make html;`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the web3@1.0.0-beta.38 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/levin/.npm/_logs/2019-01-28T11_28_10_130Z-debug.log
```

So one needs to globally install `sphinx-build` on the local machine? Kind of a bad setup. Is it not possible to install this via npm?

2019-01-28 11:29 UTC, levino requested changes

2019-01-28 11:29 UTC, levino commented on packages/web3-core-method/lib/methods/AbstractMethod.js
> +        return isString(parameter) && parameter.startsWith('0x') === 0;
I do not see a test changed for this. This is troubling. Either there is no test or the test does not test anything. How could it have worked before? Also I consider this a mix of concerns: I thought this PR is about the docs, now I see code changes. I think the code changes should be moved to another PR.

2019-01-28 11:32 UTC, Levino commented
So I will be waiting for you to get back on my comments / questions. Please at least add a "how to run locally".

2019-01-28 11:55 UTC, nivida commented
Thanks for your feedback. Yes, I know the documentation setup is not good. The goal of this PR is to add an additional section to the documentation, any other improvements will be done later. The focus currently is on bugs and to add the Web3 Moudle API documentation.

You do not have to checkout the branch for reviewing the content of the documentation. It's also possible to view them directly on [github](https://github.com/ethereum/web3.js/blob/95087d6b1977f9ff07824d083b3c457f00ec00b0/docs/include_web3-module-abstract-method-class-reference.rst).

2019-01-28 12:10 UTC, Levino commented
So it is just markdown.

2019-01-28 12:11 UTC, Levino commented
I think it would be much easier if you created one PR for each point in your list above. Having so many issues in one PR is very confusing.

2019-01-28 12:23 UTC, Levino commented
I do not understand what the point of this PR should be. Could you please verbosely explain the issue that you are trying to solve?

Before merging this PR: Who wants to do what?

Then I can see whether or not that person achieves what they wanted to do after this PR has been merged.

2019-01-28 14:33 UTC, nivida commented
I only asked if you could read the documentation and tell me if you can understand the content of it without any additional information. The point of this PR is to document the Web3 Module API as the title already says. 

If you find the time could you quickly read through the document and tell me if you could create a module with the provided information or not?

2019-01-28 15:55 UTC, Levino commented
What is a module and why would I create one? I really cannot follow. It is very hard because this is not embedded in the docs atm and I lack context.

2019-02-05 01:30 UTC, OFRBG commented
@Levino @nivida I'd like to chime in. I'm highly interested in making web3js documentation as readable as possible. Would it be okay if I propose a specific structure for each topic? I've been using the docs for almost two years now, and I'm relatively familiar with the problems it has.

2019-02-05 06:16 UTC, Levino commented
Please start by creating issues that describe the problems you encounter in a very understandable (I am a little slow it seems so please consider this) manner. If everyone agrees that these issues are worth fixing, you can start on the fixes.

2019-02-20 18:06 UTC, yxliang01 commented
I would say the `extend` method should have been retained until this documentation is ready... This transition makes life of developers extending web3 difficult... Maybe it's even better if the Web3 doc allows us to view the doc of older 1.0 beta versions.

2019-02-20 20:03 UTC, fixanoid commented
> I would say the `extend` method should have been retained until this documentation is ready... This transition makes life of developers extending web3 difficult... Maybe it's even better if the Web3 doc allows us to view the doc of older 1.0 beta versions.

And I would add that removing this breaks a ton of modules already in use. And while this is helpful in the longer run, it leaves many a module broken until maintainers update them or manual dependency resolution is made to the last working version. Why not leave it available and throw warnings for a while?

2019-02-21 11:12 UTC, nivida commented
> And I would add that removing this breaks a ton of modules already in use

I've removed this possibility now a month ago and explained why I removed this. Feel free to create a PR if there are is a JSON-RPC method.

> And while this is helpful in the longer run, it leaves many a module broken until maintainers update them or manual dependency resolution is made to the last working version. 

If you would like to use the ``extend`` method then please use the version beta.37.

> Why not leave it available and throw warnings for a while?

I didn't add this during the refactoring because it's really ugly and hard to test. There are also some problems with the formatters and utils modules which the ``extend`` method was indirectly depending on. 

All the details about the refactoring are explained in the release announcement of version beta.38: 
https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b

2019-05-02 19:04 UTC, merged