Fix callback types
ethereum/web3.js pull request #2672
Opened 2019-04-12 08:46 UTC by alexkvak

sendSignedTransaction returns transaction hash in callback.
contract.deploy.send returns transaction hash in callback.

2019-04-12 09:11 UTC, joshstevens19 approved these changes
Thanks for this PR. Nice spot @alexkvak - looks good :+1: @nivida can you merge please.

2019-04-12 18:01 UTC, princesinha19 requested changes
Thanks for this PR @alexkvak.

2019-04-12 18:04 UTC, princesinha19 requested changes

2019-04-12 18:04 UTC, princesinha19 commented on packages/web3-eth-contract/types/tests/contract-test.ts
> +}).send({from: '0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe'}, (err: Error, hash: string) => { console.log(hash) });
I would like to change hash to **transactionHash** to make it more clear.

2019-04-12 18:04 UTC, princesinha19 commented on packages/web3-eth/types/index.d.ts
> +    sendSignedTransaction(signedTransactionData: string, callback?: (error: Error, hash: string) => void): PromiEvent<TransactionReceipt>
same here.

2019-04-12 18:04 UTC, princesinha19 commented on packages/web3-eth/types/tests/eth.tests.ts
> +eth.sendSignedTransaction('0xf889808609184e72a0008227109', (error: Error, hash: string) => {});
same here. can you please change hash to **transactionHash**

2019-04-14 15:29 UTC, nivida approved these changes

2019-04-14 15:29 UTC, merged