Adapts checksum functionality to RSKIP60 and EIP55
ethereum/web3.js pull request #2727
Opened 2019-04-24 15:32 UTC by alepc253

## Description

This PR adapts checksum functionality to [RSKIP-60](https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP60.md) compatible with  [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md).
The implementation considers sending optional `chainId` parameter to checksum methods (with `chainId = null` as default, Ethereum checksum is applied).

Benefit

- Allows checksum implementation in any network.
- Can distinguish between testnets and mainnets.

## Type of change

- [ ] Bug fix 
- [X] New feature 
- [ ] Breaking change
- [X] Enhancement

## Checklist:

- [X] I have selected the correct base branch.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no warnings.
- [X] I have updated or added types for all modules I've changed
- [X] Any dependent changes have been merged and published in downstream modules.
- [X] I ran ```npm run test``` in the root folder with success and extended the tests if necessary.
- [X] I ran ```npm run build``` in the root folder and tested it in the browser and with node.
- [X] I ran ```npm run dtslint``` in the root folder and tested that all my types are correct
- [ ] I have tested my code on an ethereum test network.

2019-04-24 19:30 UTC, nivida requested changes
Thanks for submitting this PR! 

Could you update the related documentation and the types for both methods?

2019-04-25 15:16 UTC, nivida requested changes

2019-04-25 15:16 UTC, nivida commented on docs/_build/html/_sources/web3-utils.rst.txt
> +2. ``chainId`` - ``number`` (optional): Chain id where checksummed address should be valid, defaults to ``null``.
Thanks for extending the documentation! Could you add here the URL to the RSKIP-60 spec?

2019-04-25 15:16 UTC, nivida commented on docs/_build/html/_sources/web3-utils.rst.txt
> +stripHexPrefix
Could you add the required test cases in the web3-utils module for this method?

2019-04-25 15:16 UTC, nivida commented on docs/_build/html/_sources/web3-utils.rst.txt
> +2. ``chainId`` - ``number`` (optional): Chain id where checksummed address should be valid, defaults to ``null``.
Could you add here the URL to the RSKIP-60 spec?

2019-04-25 15:16 UTC, nivida commented on packages/web3-utils/src/Utils.js
> +        let output = parseInt(keccakHash[i], 16) >= 8 ?
Could you change this line to: 
`` let output = parseInt(keccakHash[i], 16) >= 8 ?
            stripAddress[i].toUpperCase() :
            stripAddress[i].toLowerCase();
``

2019-04-25 15:16 UTC, nivida commented on packages/web3-utils/src/index.js
> +        checksumAddress += parseInt(keccakHash[i], 16) >= 8 ?
Could you change this line to: 
`` let output = parseInt(keccakHash[i], 16) >= 8 ?
            stripAddress[i].toUpperCase() :
            stripAddress[i].toLowerCase();
``

2019-04-25 15:24 UTC, nivida requested changes

2019-04-25 15:24 UTC, nivida commented on packages/web3-utils/types/index.d.ts
> +    toChecksumAddress(address: string, chainId?: number): string;
Could you also extend the type tests for all these changes?

2019-04-25 15:41 UTC, alepc253 commented
@nivida thanks! I'm working on your reviews.
One important aspect to consider (and still didn't boarded) is the method `inputAddressFormatter` from `web3-core-helpers/src/Formatters.js`. `chainId` should be added to that formatter to be consistent to this change. I guess it would be very helpful to have `chainId` as a global parameter but I don't know if that is possible at this level... what do you think?

2019-04-25 15:49 UTC, nivida commented
@alepc253 I would like to write that down in a new issue and to implement it later as an enhancement. The question will also be if Web3 should automatically load the ``chainId`` from the connected node if no ``chainId`` got defined from the developer.

2019-04-26 09:57 UTC, nivida approved these changes

2019-04-26 09:58 UTC, merged