Typing improvement
ethereum/web3.js pull request #2762
Opened 2019-05-01 09:47 UTC by princesinha19

## Description

Improving typing of modules.

## Type of change
- [x] Enhancement

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no warnings.
- [x] I have updated or added types for all modules I've changed
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run test``` in the root folder with success and extended the tests if necessary.
- [x] I ran ```npm run build``` in the root folder and tested it in the browser and with node.
- [ ] I ran ```npm run dtslint``` in the root folder and tested that all my types are correct
- [ ] I have tested my code on an ethereum test network.

2019-05-01 12:21 UTC, princesinha19 commented
@joshstevens19, @nivida can you please review this?

2019-05-07 12:11 UTC, princesinha19 commented
@nivida Can you please merge this?

2019-05-07 12:23 UTC, nivida requested changes

2019-05-07 12:23 UTC, nivida commented on packages/web3-eth/types/index.d.ts
> +export interface PendingTransactions extends Transaction {
I would rename ``PendingTransactions`` to ``PendingTransaction``

2019-05-28 10:42 UTC, princesinha19 commented
Could you please merge this @nivida?

2019-06-12 07:52 UTC, closed without merging

2019-07-03 19:17 UTC, princesinha19 commented
@nivida Any specific reason behind closing this PR?

2019-07-03 19:25 UTC, joshstevens19 commented
I think your going to have to do this against the 2.0 alpha branch now due to the changes of a stable 1.0. So I’m assuming he closed it but forgot to say way.. maybe you could redo this once the initial 2.0 alpha is released then we can get it merged 👍