web3-core-types against 2.x
ethereum/web3.js pull request #2910
Opened 2019-06-25 00:51 UTC by OFRBG

## Description

> Instead of having the web3-utils and web3-core-helpers module for simple validations or mappings of values does the types module combine these two modules to one clear types module.

This submodule should include type checks, parsing, and object creation for:
* [ ] ABI
* [ ] ABIItem
* [x] Address
* [ ] Ascii
* [ ] BigNumber
* [ ] Block
* [ ] Bloom
* [x] Ether
* [ ] Event
* [x] Hex
* [ ] RpcPayload
* [ ] Sha3
* [ ] SyncEvent
* [ ] Topic
* [x] Transaction
* [ ] TransactionReceipt

Fixes #2801 

## Type of change

- [x] New feature 
- [x] Breaking change
- [x] Enhancement

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no warnings.
- [ ] I have updated or added types for all modules I've changed
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran ```npm run lint``` in the root folder with success and pushed the changes.
- [ ] I ran ```npm run test``` in the root folder with success and extended the tests to cover my changes.
- [ ] I ran ```npm run build``` in the root folder and tested it in the browser and with node.
- [ ] I ran ```npm run dtslint``` in the root folder and tested that all my types are correct
- [ ] I have tested my code on an ethereum test network.

2019-07-31 11:05 UTC, nivida requested changes
I will review the other classes after we have updated the ``Address`` VO. The folder structure can also get improved later.

2019-07-31 11:05 UTC, nivida commented on packages/web3-core-types/src/Address/Address.js
> +    constructor(params) {
the type of the constructor should be: ``constructor(address: string);``.

``` typescript 
class Address {
  constructor(address) {
   this.value = address;
  }

  set value(value) {
    if (!Address.isValid(value)) {
      throw new Error('');
    }

    this._value = value;
  }

  ...
}
```

2019-07-31 11:05 UTC, nivida commented on packages/web3-core-types/src/Address/Address.js
> +    set address(value) {
I would call the accessors ``value`` because the class name does already define what kind of data value it is.

2019-07-31 11:05 UTC, nivida commented on packages/web3-core-types/src/Address/Address.js
> +    static isValid(value) {
FYI: I will check the validation closer later.

2019-07-31 11:05 UTC, nivida commented on packages/web3-core-types/src/Address/Address.js
> +        const addressHash = sha3(address.toLowerCase())
This could be moved to a ``hash`` accessor for not having duplications. (line 108 & 81)

2019-07-31 11:05 UTC, nivida commented on packages/web3-core-types/src/Address/Address.js
> +        const addressHash = sha3(address.toLowerCase())
FYI: I will check the regular expression and the mapping later.

2019-07-31 11:05 UTC, nivida commented on packages/web3-core-types/src/Address/Address.js
> +            this._isChecksummed = Address.isValid(this._address);
This line can be deleted and the non-static ``isValid`` method can wrap the static version of it.

2019-08-01 01:30 UTC, OFRBG commented on packages/web3-core-types/src/Address/Address.js
> +        const addressHash = sha3(address.toLowerCase())
Since we need an `isValid` static method, I've declared a method called `hashAddress::string => string`.

2019-08-10 08:06 UTC, nivida commented
I have to close this PR because I've started to create the type objects already. This because they are required for the public API layer improvements I've mentioned in issue #2639.

PR: https://github.com/ethereum/web3.js/pull/3020

2019-08-10 08:06 UTC, closed without merging