WebsocketProviderOptions has been adjusted
ethereum/web3.js pull request #2983
Opened 2019-07-30 16:36 UTC by AsyncLegs

requestOptions field has added: more info - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/websocket/index.d.ts

2019-07-31 09:42 UTC, nivida requested changes
The types you were editing are for the 2.x architecture but the [PR](https://github.com/ethereum/web3.js/pull/2979) you opened with the ``requestOptions`` addition is for the 1.0 architecture. The ``requestOptions`` can be added to the [createWebsocketProvider](https://github.com/ethereum/web3.js/blob/2.x/packages/web3-providers/src/factories/ProvidersModuleFactory.js#L136) method of the [ProvidersModuleFactory](https://github.com/ethereum/web3.js/blob/2.x/packages/web3-providers/src/factories/ProvidersModuleFactory.js#L136) if you would like to add this addition also in 2.0.

2019-07-31 09:53 UTC, AsyncLegs commented
Oh sorry, just missed a bit, because a reconnect [method](https://github.com/ethereum/web3.js/blob/2.x/packages/web3-providers/src/providers/WebsocketProvider.js#L100)  has this option already

2019-08-02 10:47 UTC, nivida requested changes

2019-08-02 10:47 UTC, nivida commented on packages/web3-providers/src/factories/ProvidersModuleFactory.js
> +            const requestOptions = options.requestOptions || null;
```suggestion

```

2019-08-02 10:47 UTC, nivida commented on packages/web3-providers/src/factories/ProvidersModuleFactory.js
> +            connection = new W3CWebsocket(url, options.protocol, null, headers, requestOptions, options.clientConfig);
```suggestion
            connection = new W3CWebsocket(url, options.protocol, null, headers, options.requestOptions, options.clientConfig);
```

2019-08-02 20:07 UTC, merged