Update subscription.js
ethereum/web3.js pull request #3028
Opened 2019-08-15 19:16 UTC by lbertenasco

Would something like this be possible to add?
It's useful when testing WS subscriptions successful connections.
Instead of retrying get `subscription.id` until it's defined.

2019-08-16 08:56 UTC, nivida commented
This could be added to a provider. The new 2.0 socket-based provider does already have that.

2019-10-15 12:05 UTC, nivida requested changes
Thanks for proposing this PR! Could you please update the changelog file located in the root folder of this branch? and also extend the documentation?

2019-10-17 05:15 UTC, lbertenasco commented
> Thanks for proposing this PR! Could you please update the changelog file located in the root folder of this branch? and also extend the documentation?

Changelog and docs updated 👍

2019-10-17 15:41 UTC, nivida approved these changes

2019-10-17 15:42 UTC, merged