fix(eth-abi): encodeParam string type to keccak256
ethereum/web3.js pull request #3061
Opened 2019-09-09 16:47 UTC by YegorZaremba

Fixes: #3053 

Right now only [EventFilterEncoder](https://github.com/ethereum/web3.js/blob/2.x/packages/web3-eth-contract/src/encoders/EventFilterEncoder.js#L52) calls `encodeParameter` method

I decided in this way, but if you have any suggestion, I could change this PR

2019-09-09 17:05 UTC, nivida commented
Hey! Thanks for opening this PR. I've just checked the bug closer and forgot about that dynamically allocated types as for example ``string`` can't be defined as indexed event property. ([stackexchange discussion about](https://ethereum.stackexchange.com/questions/6840/indexed-event-with-string-not-getting-logged/7170#7170))

2019-09-09 17:38 UTC, nivida commented
re-opened it: It will add event properties that are indexed but dynamically allocated types of event properties to the ``data`` array and it creates a hash of it and adds the hash to the ``topics`` array.

The ``encodeParameter`` method is exposed also in the public API of the ``AbiCoder`` which is accessible over ``web3.eth.abi.encodeParameter``. This means that this fix should be applied in the ``EventFilterEncoder``. I apologize for the confusion.

2019-09-10 19:10 UTC, YegorZaremba commented
- [x] Tested with single string value on Rinkeby network
- [x] Tested with array of string values on Rinkeby network

At first, I would like to make private method, but didn't find any this type of methods in web3.js lib. Then I thought about static method, but only `encode` method will use it. So I decided to do "private" closure like [here](https://github.com/ethereum/web3.js/blob/2.x/packages/web3-eth-iban/src/Iban.js#L31), if I wrong, please let me know, I'll fix it

code to test

```js
const Web3 = require('web3')
const web3 = new Web3(new Web3.providers.WebsocketProvider('wss://rinkeby.infura.io/ws'))

const CONTRACT_ADDRESS = '0x8f044afc2202ea44790f0081ea964b02f05783bd'
const CONTRACT_ABI = [ { "constant": false, "inputs": [ { "name": "_str", "type": "string" } ], "name": "click", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "anonymous": false, "inputs": [ { "indexed": true, "name": "a", "type": "address" }, { "indexed": true, "name": "b", "type": "string" }, { "indexed": true, "name": "c", "type": "uint256" } ], "name": "CatchMeIfYouCan", "type": "event" } ];

(() => {
  const contract = new web3.eth.Contract(CONTRACT_ABI, CONTRACT_ADDRESS)
  contract.events.CatchMeIfYouCan({
      filter: {b: ['qwerty', 'second']},
      fromBlock: 5000000
  }, (__, event) => {
    console.log('_____filter_____')
    console.log(event)
  })
})()

```

2019-10-08 12:28 UTC, nivida requested changes

2019-10-08 12:28 UTC, nivida commented on packages/web3-eth-contract/src/encoders/EventFilterEncoder.js
> +const encodeParameter = (type, param, abiCoder) => {
On the second look after my vacation is it probably better to extend the ``AbiCoder`` with an ``encodeTopic`` method and to handle all dynamically allocated types. Sorry.

Private methods do currently not in web3.js but will be added asap. 

Proposals for private properties and methods:
- https://github.com/tc39/proposal-private-methods 
    + https://babeljs.io/docs/en/babel-plugin-proposal-private-methods
- https://github.com/tc39/proposal-private-fields
    + https://babeljs.io/docs/en/babel-plugin-proposal-class-properties

2019-11-05 15:22 UTC, nivida requested changes

2019-11-05 15:22 UTC, nivida commented on packages/web3-eth-abi/src/AbiCoder.js
> +        if (type === 'string' || type === 'string[]') {
Thanks for doing those changes! 

The cases for ``bytes``, ``structs`` and ``Array``'s (dynamically and statically) are missing. The solidity documentation does describe all the encoding rules [here](https://solidity.readthedocs.io/en/v0.5.12/abi-spec.html#encoding-of-indexed-event-parameters).

2019-11-22 19:30 UTC, YegorZaremba commented
I see that 1.x.x branch went far ahead, not sure that 2.x.x branch will alive in this state, so I close this PR for clean purposes

2019-11-22 19:30 UTC, closed without merging