Use eth_chainId when signing transactions
ethereum/web3.js pull request #3097
Opened 2019-10-03 23:21 UTC by cgewecke

Addresses #2738 and #1169 for the 1.x branch. Makes web3 conform to [EIP 155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) and fetch chainId via `eth_chainId` instead of `net_version`. For ethereum public nets there's no problem here because network id == chain id. For ganache, ETC and possibly others - the two values are different. 

Note: these endpoints return their ids in different formats:

| Client       | net_version     | eth_chainId |
|--------------|-----------------|-------------|
| geth --dev   | "1337"          | "0x539"     |
| parity --dev | "17"            | "0x11"      |
| ganache-cli  | "1570135120814" | "0x539"     |

`eth_chainId` is not documented in the JSON_RPC spec. This is a case where it would be nice to have E2E tests vs the three main clients to be sure Web3's mocked responses correspond to reality.

2019-10-07 20:31 UTC, gabmontes commented
@cgewecke these changes are good IMHO.

I've been patching beta 37 with this exact set of changes in several [Metronome](https://github.com/autonomoussoftware) projects for quite some time and works flawlessly.

Hope this is merged soon.

2019-10-07 22:55 UTC, cgewecke commented
Thanks @gabmontes, good to know.

2019-10-08 00:16 UTC, nivida requested changes
Could you update the changelog for this and all other PRs you proposed?

2019-10-08 00:57 UTC, cgewecke commented
@nivida Do want the changelog updated under 1.2.3? Or unreleased?

2019-10-08 01:03 UTC, nivida commented
„Unreleased“ is just the tag to label the unreleased version and the related changes. You can just extend the list of 1.2.2. @cgewecke

2019-10-08 02:47 UTC, cgewecke commented
@nivida Oh I just remembered something - not sure how you do this exactly but there is a nice npm utility called [changelog](https://www.npmjs.com/package/changelog) that helps you generate a version-based changelog in one post-publication step. 

The output still needs to be edited etc, but it seems like a convenient way of avoiding merge conflicts when there are lots of small PRs queued up like this and they all modify the same file.

2019-10-08 04:34 UTC, nivida commented
@cgewecke Let us discuss this in an issue. :)

2019-10-08 04:37 UTC, nivida approved these changes

2019-10-08 04:37 UTC, merged