Block interface changes to fix typing
ethereum/web3.js pull request #3152
Opened 2019-10-23 15:15 UTC by princesinha19

I have changed the interface of getBlock and getUncle to solve issue #3150. I have changed the type of **returnTransactionObjects** from `boolean` to `true` because by default it's false so, there is no need to specify that. Let us know if anyone thinks the previous one was better.

2019-10-28 17:20 UTC, joshstevens19 requested changes

2019-10-28 17:20 UTC, joshstevens19 commented on packages/web3-eth/types/index.d.ts
> +export interface BlockTransactionObject extends BlockHeader {
you could probably make a base interface like `BlockTransactionBase` which extends `BlockHeader` which has all the repeating ones like size, difficulty, totalDifficulty and uncles and then just define transactions like:

```
interface BlockTransactionBase extends BlockHeader {
   size: number;
    difficulty: number;
    totalDifficulty: number;
    uncles: string[];
}

export interface BlockTransactionObject extends BlockTransactionBase {
   transactions: Transaction[];
}

export interface BlockTransactionString extends BlockTransactionBase {
   transactions: string[];
}
```

and means you only got 1 place to change the shared properties :+1:

2019-11-05 14:39 UTC, nivida commented on docs/web3-eth.rst
> +2. ``True`` - (optional, default ``false``) If specified ``true``, the returned block will contain all transactions as objects. By default it is ``false`` so, there is no need to explictly specify fa
```suggestion
2. ``Boolean`` - (optional, default ``false``) If specified ``true``, the returned block will contain all transactions as objects. By default it is ``false`` so, there is no need to explictly specify false. And, if ``false`` it will only contains the transaction hashes.
```

2019-11-05 14:39 UTC, nivida commented on docs/web3-eth.rst
> +3. ``True`` - (optional, default ``false``) If specified ``true``, the returned block will contain all transactions as objects. By default it is ``false`` so, there is no need to explictly specify fa
```suggestion
3. ``Boolean`` - (optional, default ``false``) If specified ``true``, the returned block will contain all transactions as objects. By default it is ``false`` so, there is no need to explictly specify false. And, if ``false`` it will only contains the transaction hashes.
```

2019-11-05 14:40 UTC, nivida approved these changes

2019-11-05 16:45 UTC, nivida requested changes
The CI is failing with the error ``strict-export-declare-modifiers`` [here](https://travis-ci.org/ethereum/web3.js/jobs/607670594#L798-L799).

2019-11-06 10:08 UTC, nivida approved these changes

2019-11-06 10:09 UTC, merged