Internal improvement: Add & adjust web3-core-helper typings
ethereum/web3.js pull request #3177
Opened 2019-11-05 00:19 UTC by CruzMolina

2019-11-05 13:48 UTC, nivida requested changes
Thanks for proposing this PR! I've added some suggestions with required changes.

2019-11-05 13:48 UTC, nivida commented on packages/web3-core-helpers/types/index.d.ts
> +    ): any;
```suggestion
    ): void;
```

2019-11-05 13:48 UTC, nivida commented on packages/web3-core-helpers/types/index.d.ts
> +    ): any;
```suggestion
    ): void;
```

2019-11-05 13:48 UTC, nivida commented on packages/web3-core-helpers/types/index.d.ts
> +    ): any;
```suggestion
    ): void;
```

2019-11-05 16:47 UTC, nivida approved these changes

2019-11-05 17:56 UTC, cgewecke reviewed
@CruzMolina Thanks! Just have a couple questions...

Does this resolve the `tsc` errors you've been seeing in [truffle 2488][4]?

The provider bases look like they are defined in the core-helpers but extended in 
+ [web3-provider-http][1]
+ [web3-provider-ws][2]
+ [web3-provider-ipc][3]

The types there retain the format you've changed here. Will that be an issue - a more generic overloading in an inheriting type?

Those packages also contain types tests for the providers. Is it possible to write a `Callback` type example there so that future changes get caught for a closer check?

To be clear - would gladly defer to anyone with greater TS experience than I have - these are **genuinely questions** :)

[1]: https://github.com/ethereum/web3.js/blob/1.x/packages/web3-providers-http/types/index.d.ts#L29-L43
[2]: https://github.com/ethereum/web3.js/blob/1.x/packages/web3-providers-ws/types/index.d.ts#L43-L46
[3]: https://github.com/ethereum/web3.js/blob/1.x/packages/web3-providers-ipc/types/index.d.ts#L38-L41
[4]: https://github.com/trufflesuite/truffle/pull/2488

2019-11-05 18:36 UTC, CruzMolina commented
Ah, thanks for the heads up regarding the extensions @cgewecke.

Not sure if the typings added here will cause issues, but for consistency sake it makes sense to import these & implement the typings for each `Provider` class appropriately (along with adding tests).

Btw, this isn't a blocker on our end. We've been using the `@types/web3` typings and are in the process of migrating over so we can upgrade to latest.

2019-11-05 19:51 UTC, cgewecke approved these changes
@nivida Thanks for those tests, awesome. Are you fine with the overloading back to the old form in providers types files? 

Otherwise LGTM!

2019-11-05 20:28 UTC, nivida commented
@cgewecke Thanks for the hint! I've updated the tests and type definitions in those packages. 👌

2019-11-05 20:35 UTC, cgewecke approved these changes
Yeah! Make sense to me! @CruzMolina Are you happy with the added changes? Want to take second look?

2019-11-05 22:01 UTC, CruzMolina commented
I think typing the callback as I originally had it makes more sense (`Callback<JsonRpcResponse>`), but I can just type locally in one of our pkgs where we use the callback.

2019-11-06 08:54 UTC, nivida commented
@CruzMolina The reason for those changes was that ``dtslint`` tests were failing with the ``Callback<JsonRpcResponse>`` type definition and just worked because the ``send`` method got overwritten in the provider packages:)

2019-11-06 10:52 UTC, merged