Fix typescript definition for eth.getStorageAt
ethereum/web3.js pull request #3180
Opened 2019-11-05 19:26 UTC by spalladino

The position parameter was set as number, but a string is required to specify a position for a slot with a large index (ie greater than 53 bits) since it requires more precision that js max int.

2019-11-05 19:35 UTC, nivida requested changes
Thanks for proposing this PR! 
By side of the suggested change do we have to update the documentation [here](https://web3js.readthedocs.io/en/v1.2.2/web3-eth.html#getstorageat) and the tests for those types as well.

2019-11-05 19:35 UTC, nivida commented on packages/web3-eth/types/index.d.ts
> +        position: number | string,
It's possible to pass a ``number``, ``string``, or ``BN`` value as position.

```suggestion
        position: number | string | BN,
```

2019-11-05 21:07 UTC, spalladino commented
Updated! Added a test as well to check that it works correctly with bignumber.js.

2019-11-12 12:40 UTC, nivida commented
@spalladino 
> Updated! Added a test as well to check that it works correctly with bignumber.js.

I think you forgot to push those changes:)

2019-11-12 15:06 UTC, spalladino commented
:man_facepalming:

2019-11-13 09:30 UTC, nivida requested changes
I've added the required changes as suggestions. Please check those and apply them if you agree or drop a comment if not.

2019-11-13 09:30 UTC, nivida commented on packages/web3-eth/types/index.d.ts
> +import { BigNumber } from 'bignumber.js';
```suggestion
import { BN } from 'bn.js';
```

2019-11-13 09:30 UTC, nivida commented on packages/web3-eth/types/index.d.ts
> +    getStorageAt(address: string, position: number | BigNumber | string): Promise<string>;
```suggestion
    getStorageAt(address: string, position: number | BN | string): Promise<string>;
```

2019-11-13 09:30 UTC, nivida commented on packages/web3-eth/types/index.d.ts
> +        position: number | BigNumber | string,
```suggestion
        position: number | BN | string,
```

2019-11-13 09:30 UTC, nivida commented on packages/web3-eth/types/index.d.ts
> +        position: number | BigNumber | string,
```suggestion
        position: number | BN | string,
```

2019-11-13 09:30 UTC, nivida commented on packages/web3-eth/types/index.d.ts
> +        position: number | BigNumber | string,
```suggestion
        position: number | BN | string,
```

2019-11-13 09:30 UTC, nivida commented on test/eth.getStorageAt.js
> +var BN = require('bignumber.js');
```suggestion
var BN = require('bn.js');
```

2019-11-13 09:30 UTC, nivida commented on docs/web3-eth.rst
> +2. ``Number|String`` - The index position of the storage.
```suggestion
2. ``Number|String|BN`` - The index position of the storage.
```

2019-11-13 09:30 UTC, nivida commented on docs/_build/html/web3-eth.html
> +<li><code class="docutils literal"><span class="pre">Number|String</span></code> - The index position of the storage.</li>
The build file can get removed because ``readthedocs`` isn't using the provided build it does run the ``docs`` build pipeline on its own.

2019-11-13 09:30 UTC, nivida commented on docs/_build/html/_sources/web3-eth.txt
> +2. ``Number|String`` - The index position of the storage.
```suggestion
2. ``Number|String|BN`` - The index position of the storage.
```

2019-11-13 10:23 UTC, nivida commented on test/eth.getStorageAt.js
> +}, {
Could you add the BigNumber case as well? (Sorry noticed it later that BN and BigNumber are supported)

2019-11-14 12:30 UTC, nivida approved these changes

2019-11-14 13:14 UTC, merged

2019-11-14 22:38 UTC, spalladino commented
Thanks for wrapping it up and merging!