Internal improvement: Adjust typings to allow an empty Web3 constructor
ethereum/web3.js pull request #3184
Opened 2019-11-06 17:53 UTC by CruzMolina

2019-11-06 17:54 UTC, gnidan approved these changes

2019-11-06 18:22 UTC, joshstevens19 requested changes

2019-11-06 18:22 UTC, joshstevens19 commented on packages/web3/types/index.d.ts
> +    constructor(provider?: provider, net?: net.Socket);
Thanks for this, your change will make the typings not as clean you would want, can you please overload them like:

```
constructor(provider: provider);
constructor(provider: provider, net: net.Socket);
constructor(net: net.Socket);
constructor();
```

and then write some tests for them please.

2019-11-06 22:44 UTC, joshstevens19 requested changes

2019-11-06 22:44 UTC, joshstevens19 commented on packages/web3/types/tests/web3-test.ts
> +const netSocket = new net.Socket();
Can you move these to the bottom so they don’t effect the main tests  and then use the the expect type syntax to test it.

Like:

$ExpectType Web3
web3 = new Web3()

$ExpectType Web3
web3 = new Web3(‘https://localhost:5000/‘, netSocket)

Above the new web3 that you create. Then looks good to merge.

2019-11-07 08:08 UTC, joshstevens19 approved these changes
LGTM

2019-11-07 09:57 UTC, nivida approved these changes

2019-11-07 09:57 UTC, merged