Refractoring/contracts
ethereum/web3.js pull request #3362
Opened 2020-02-03 17:16 UTC by helderjnpinto

## Description

Just changed unecessary else return blocks, fix typos in comments, and added a default in switch for throwing a not implemented method error. 

## Type of change

Refractoring code

## Checklist:

- [x ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run dtslint``` with success and extended the tests and types if necessary.
- [x] I ran ```npm run test:unit``` with success and extended the tests if necessary.
- [x] I ran ```npm run build-all``` and tested the resulting file/'s from  ```dist``` folder in a browser.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the live network.

2020-02-03 18:35 UTC, nivida commented
@helderjnpinto Thanks for applying those required improvements! I will review it tomorrow 💪

2020-02-04 09:58 UTC, nivida requested changes
LGTM! I've just added a suggestion to remove unnecessary line breaks.

2020-02-04 09:58 UTC, nivida commented on packages/web3-eth-contract/src/index.js
> +            throw new Error('Method "' + args.type + '" not implemented.');
Could you if you open another PR for this project reference additions like this newly added error in the description of the pull request?

2020-02-04 09:58 UTC, nivida commented on packages/web3-eth-contract/src/index.js
> +
Those line breaks aren't required and can get removed.
```suggestion
```

2020-02-04 09:58 UTC, nivida commented on packages/web3-eth-contract/src/index.js
> +
```suggestion
```

2020-02-05 06:43 UTC, cgewecke approved these changes
LGTM! Thanks @helderjnpinto.

2020-02-05 14:04 UTC, nivida approved these changes

2020-02-05 14:04 UTC, merged