Update README.md
ethereum/web3.js pull request #3807
Opened 2020-12-07 01:24 UTC by zimmah

Add a little clarification to the readme.

2021-01-07 09:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/web3.js?pullRequest=3807) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/web3.js?pullRequest=3807) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/web3.js?pullRequest=3807) it.</sub>

2021-01-11 19:26 UTC, spacesailor24 commented on packages/web3-providers-ipc/README.md
> +Note: make sure to run [geth](https://geth.ethereum.org/).
```suggestion
Note: make sure to run [geth](https://geth.ethereum.org/) and for information on IPCs click [here](https://ethereum.stackexchange.com/questions/1492/when-is-the-geth-ipc-file-produced)
```

2021-01-12 14:03 UTC, zimmah commented on packages/web3-providers-ipc/README.md
> +Note: make sure to run [geth](https://geth.ethereum.org/).
Thanks for the addition

2021-02-01 14:59 UTC, spacesailor24 requested changes
Can you update the `CHANGELOG.md`? After doing that, this will be ready to merge!

2021-06-13 00:10 UTC, closed without merging