add nvmrc file
ethereum/web3.js pull request #3817
Opened 2020-12-15 23:53 UTC by frankiebee

currently web3js will not successfully install deps with node version 15~ and npm version 7

please feel free to debate the node version am very willing to change this 

or weather we should specify in package.json file

2021-01-07 09:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/web3.js?pullRequest=3817) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/web3.js?pullRequest=3817) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/web3.js?pullRequest=3817) it.</sub>

2021-01-11 21:10 UTC, spacesailor24 approved these changes
I've tested installing web3 as a dependency using node `15.5.1`, and it works fine. However, installing the `devDependencies` with version `15.5.1` is broken, so I think adding the `.nvmrc` file with version `14.15.1` makes sense for developers of web3

2021-02-10 04:59 UTC, koraykoska approved these changes, later dismissed
Tested it and works for me.

2021-03-09 23:21 UTC, spacesailor24 requested changes
Needs changelog update :)

2021-03-16 02:19 UTC, spacesailor24 approved these changes

2021-03-16 22:25 UTC, spacesailor24 approved these changes

2021-03-16 22:28 UTC, merged