added remote node provider documentation edits
ethereum/web3.js pull request #3899
Opened 2021-02-03 23:12 UTC by smudgil

## Description

Forgot to update changelog with my edits of adding remote node provider documentation

2021-02-03 23:13 UTC, smudgil commented
Just updated the change.log! Please let me know if there are any issues :)

2021-02-04 17:31 UTC, GregTheGreek requested changes

2021-02-04 17:31 UTC, GregTheGreek commented on CHANGELOG.md
> +- Edited documentation to include how to use Web3 with a remote node provider
Can you kindly add the PR number assosiated with the change.

In this case please add (#old_pr / #3899)

2021-02-10 05:18 UTC, koraykoska commented
Isn't this #3884 ? Why do you have 3 PRs for the same thing? Please include all into one PR

2021-02-10 05:18 UTC, closed without merging