add berlin tx support
ethereum/web3.js pull request #4083
Opened 2021-05-25 17:32 UTC by GregTheGreek

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2021-05-27 21:25 UTC, luu-alex submitted a review, later dismissed

2021-05-31 19:23 UTC, spacesailor24 requested changes
The `dist/` files were updated, but should only be updated upon release, otherwise, it looks good!

2021-05-31 19:25 UTC, spacesailor24 commented on test/eth.accounts.signTransaction.js
> +            // for gasPrice = 0
Should this be removed?

2021-05-31 19:25 UTC, spacesailor24 commented on test/eth.accounts.signTransaction.js
> +        // for gasPrice = 0
Should this be removed?

2021-06-09 15:20 UTC, GregTheGreek commented
Currently blocked by [EthereumJS#1292](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1292) but local testing shows it solves our problems :confetti_ball:

2021-06-14 14:17 UTC, closed without merging