Add BigNumber formatter to baseFeePerGas in returned blocks - Closes #4326
ethereum/web3.js pull request #4330
Opened 2021-09-15 23:01 UTC by spacesailor24

Closes #4326

As mentioned previously, this is technically a breaking change

2021-09-16 08:20 UTC, nazarhussain submitted a review, later dismissed

2021-09-16 10:07 UTC, jdevcs commented
lgtm, also doc update [this](https://web3js.readthedocs.io/en/v1.5.2/web3-eth.html#getblock )

2021-09-16 18:20 UTC, philknows commented
This will be a breaking change. Will need to disseminate information out via community channels before merging.

2021-09-20 11:48 UTC, jdevcs requested changes
also update [BlockHeader](https://github.com/ChainSafe/web3.js/issues/4326#issuecomment-922442244) as mentioned by [this](https://github.com/ChainSafe/web3.js/issues/4326#issuecomment-922442244)

2021-09-22 11:38 UTC, jdevcs submitted a review, later dismissed

2021-09-22 11:49 UTC, nazarhussain approved these changes, later dismissed

2021-09-22 17:31 UTC, luu-alex approved these changes, later dismissed

2021-09-23 10:34 UTC, jdevcs approved these changes

2021-09-24 03:45 UTC, luu-alex approved these changes

2021-09-24 04:11 UTC, merged