Web3-utils string manipulation closes #4352
ethereum/web3.js pull request #4415
Opened 2021-10-01 03:45 UTC by luu-alex

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2021-10-06 02:59 UTC, spacesailor24 commented on packages/web3-utils/test/fixtures/stringManipulation.ts
> +    [[BigInt('9007199254740992'),32,'0'],'0x00000000000000000020000000000000'],
```suggestion
    [[BigInt('9007199254740992'),32,'0'],'0x00000000000000000020000000000000'],
    [[9007199254740992n,32,'0'],'0x00000000000000000020000000000000'],
```

Add test case for alternative syntax for BigInt

2021-10-06 02:59 UTC, Spacesai1or commented on packages/web3-utils/test/fixtures/stringManipulation.ts
> +    [[BigInt('-9007199254740992'),32,'0'],'-0x00000000000000000020000000000000'],
```suggestion
    [[BigInt('-9007199254740992'),32,'0'],'-0x00000000000000000020000000000000'],
    [[-9007199254740992n,32,'0'],'-0x00000000000000000020000000000000'],
```

Add test case for alternative syntax for BigInt

2021-10-06 02:59 UTC, spacesailor24 commented on packages/web3-utils/test/fixtures/stringManipulation.ts
> +    [[BigInt(10000),8,'0'],'0x27100000'],
```suggestion
    [[BigInt(10000),8,'0'],'0x27100000'],
    [[10000n,8,'0'],'0x27100000'],
```

Add test case for alternative syntax for BigInt

2021-10-06 03:00 UTC, spacesailor24 commented on packages/web3-utils/test/fixtures/stringManipulation.ts
> +    [[BigInt(-14),8,'0'],'-0xe0000000'],
```suggestion
    [[BigInt(-14),8,'0'],'-0xe0000000'],
    [[-14n,8,'0'],'-0xe0000000'],
```

2021-10-06 03:00 UTC, spacesailor24 commented on packages/web3-utils/test/fixtures/stringManipulation.ts
> +    [BigInt('9007199254740992'), '0x0000000000000000000000000000000000000000000000000020000000000000'],
```suggestion
    [BigInt('9007199254740992'), '0x0000000000000000000000000000000000000000000000000020000000000000'],
    [9007199254740992n, '0x0000000000000000000000000000000000000000000000000020000000000000'],
```

2021-10-06 03:00 UTC, Spacesai1or commented on packages/web3-utils/test/fixtures/stringManipulation.ts
> +    [BigInt('-9007199254740992'),'0xffffffffffffffffffffffffffffffffffffffffffffffffffe0000000000000'],
```suggestion
    [BigInt('-9007199254740992'),'0xffffffffffffffffffffffffffffffffffffffffffffffffffe0000000000000'],
    [-9007199254740992n,'0xffffffffffffffffffffffffffffffffffffffffffffffffffe0000000000000'],
```

2021-10-06 03:02 UTC, spacesailor24 requested changes
Add tests for `leftPad` and `rightPad` for sanity

2021-10-06 14:15 UTC, nazarhussain requested changes

2021-10-06 14:15 UTC, nazarhussain commented on packages/web3-utils/src/stringManipulation.ts
> +export const padLeft = (value: Numbers | string, characterAmount: number, sign = "0"): string => {
The `Numbers` type already contain `string` so you don't need to specify here.

2021-10-06 14:15 UTC, nazarhussain commented on packages/web3-utils/src/stringManipulation.ts
> +export const padLeft = (value: Numbers | string, characterAmount: number, sign = "0"): string => {
Please add validation for the input values and throw error if its not valid.

2021-10-06 14:15 UTC, nazarhussain commented on packages/web3-utils/src/stringManipulation.ts
> +    return prefix.concat(hexValue.padStart(characterAmount, sign));
Prefer using string interpolation over function calls.

2021-10-06 14:15 UTC, nazarhussain commented on packages/web3-utils/src/stringManipulation.ts
> +    return padLeft(numberToHex(v+BigInt(2**256+1)),64);
The value `2**256+1` is larger than `Number.MAX_SAFE_INTEGER`, would be safer to do this calculation with big integers. `2n ** 256n + 1n`. And also this is value is never gonna change, so would be nice to store as constant once, will improve performance.

2021-10-06 14:15 UTC, nazarhussain commented on packages/web3-utils/src/stringManipulation.ts
> +    if (val >= 0) return padLeft(toHex(val),64);
For my knowledge, why are we enforcing for a 32 byte value here?

2021-10-06 18:31 UTC, luu-alex commented on packages/web3-utils/src/stringManipulation.ts
> +    if (val >= 0) return padLeft(toHex(val),64);
I'm not too sure. @spacesailor24, would you happen to know?

2021-10-07 17:33 UTC, luu-alex commented on packages/web3-utils/src/stringManipulation.ts
> +    if (val >= 0) return padLeft(toHex(val),64);
From what I gathered, 32 bytes is to support the default size of solidity's type `int`/`uint256`

2021-10-08 00:51 UTC, Spacesai1or commented on packages/web3-utils/src/stringManipulation.ts
> +    if (val >= 0) return padLeft(toHex(val),64);
I can't directly link to the method description, so scroll down or search for search `Two's Complement` [here](https://docs.ethers.io/v5/api/utils/bignumber/#BigNumber--methods), but Ethers supports `bitwidth` as an argument, and I don't see why we couldn't as an optional parameter (with 32 bytes being default)

We should also have a `fromTwos` method

2021-10-08 10:06 UTC, nazarhussain commented on packages/web3-utils/src/stringManipulation.ts
> +    if (val >= 0) return padLeft(toHex(val),64);
Yes I agree to @spacesailor24 we should add an extra attribute `bitwidth` with default value.

2021-10-08 10:07 UTC, nazarhussain approved these changes
Apart from @spacesailor24 comment LGTM. Also please rename the file to underscore format. `stringManipulation.ts` -> `string_manipulation.ts`

2021-10-12 14:44 UTC, luu-alex commented on packages/web3-utils/src/stringManipulation.ts
> +    if (val >= 0) return padLeft(toHex(val),64);
Thanks for the feedback, the `toTwos` function now also takes in a `nibbleWidth` because this function returns a hexstring and a hexstring is 4 bits.

I was thinking about the `fromTwos` method and its primarily used for converting binary data into the appropriate decimal, since `toTwos` returns a hexstring, `fromTwos` isn't going to be useful as we can just use `toNumber` to turn a hexstring into a decimal

2021-10-12 19:58 UTC, Spacesai1or commented on packages/web3-utils/src/errors.ts
> +	public constructor(value: unknown) {
```suggestion
	public constructor(value: string) {
```

Based on how you use the error:

```typescript
throw new NibbleWidthError(`value: "${value}", nibbleWidth: "${nibbleWidth}"`);
```

2021-10-12 20:22 UTC, Spacesai1or commented on packages/web3-utils/test/fixtures/string_manipulation.ts
> +]
You could just make use of `padLeftInvalidData` as they are testing the same error cases with the same error messages

2021-10-13 10:44 UTC, nazarhussain commented on packages/web3-utils/test/fixtures/string_manipulation.ts
> +	[[-1000, 64], -1000],
How can the `positive` and `negative` value have same compliment?

2021-10-13 14:33 UTC, luu-alex commented on packages/web3-utils/test/fixtures/string_manipulation.ts
> +	[[-1000, 64], -1000],
This is turning the twos complement into decimals

2021-10-13 22:40 UTC, Spacesai1or approved these changes
Awesome job @luu-alex! Thank you for addressing all the feedback :rocket:

2021-10-14 00:37 UTC, merged