Init web3-providers-http  - Closes #4312
ethereum/web3.js pull request #4416
Opened 2021-10-01 07:00 UTC by spacesailor24

Closes #4312 #4371 #4373 #4379 #4380

2021-10-12 18:45 UTC, Spacesai1or commented on tools/eslint-config-web3-base/ts.js
> +		'no-shadow': ['off'],
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-shadow.md#how-to-use

2021-10-12 19:09 UTC, Spacesai1or commented on tools/eslint-config-web3-base/ts.js
> +		'no-shadow': ['off'],
This was incorrectly reporting an error for the enum defined [here](https://github.com/ChainSafe/web3.js/blob/ff716daf3f7b388bfc059b1c7b3c395fd7ef0372/packages/web3-common/src/types.ts#L5)

2021-10-13 10:40 UTC, nazarhussain requested changes
The `eth1` API is fully complaint with the [JSON-RPC](https://github.com/ethereum/execution-apis) standard, and `beacon` is using [OpenAPI](https://github.com/ethereum/beacon-APIs) standard. 

Since both standard are standalone and fully independent of each other, so let's not mix up the types for these together. 

We should look into using our other [Eth2 API package ](https://www.npmjs.com/package/@chainsafe/eth2.0-api-wrapper) internally in our provider and don't redo the work. If there is any blocker using it let's discuss.

2021-10-13 10:40 UTC, nazarhussain commented on packages/web3-common/src/types.ts
> +	readonly protocol?: SupportedProtocolsEnum.EXECUTION;
There can't exist any extra parameter in the JSON-RPC request. If you want to add some predefined params then it must go under `params`

https://www.jsonrpc.org/specification#request_object

2021-10-13 10:40 UTC, nazarhussain commented on packages/web3-common/src/types.ts
> +}
Same applies here. JSON-RPC request can't have any of these parameters. If you want to build your own request object then don't call it `JSON-RPC` request. 

https://www.jsonrpc.org/specification#request_object

2021-10-13 10:40 UTC, nazarhussain commented on packages/web3-common/src/types.ts
> +}
The existing `JsonRpcError` type was fully compliant with the specification. The Eth API is also following the specification, I don't see any reason to modify these objects. 

https://www.jsonrpc.org/specification#error_object

2021-10-19 12:12 UTC, nazarhussain requested changes

2021-10-19 12:12 UTC, nazarhussain commented on packages/web3-providers-http/src/index.ts
> +	}
You don't need this as it will be handled by the `BaseProvider` for you. 

```suggestion
```

2021-10-19 12:12 UTC, nazarhussain commented on packages/web3-providers-http/src/index.ts
> +	}
May be would be better to return `connected` status as HTTP provider always connected and `request` is not dependent on existing connection.

2021-10-19 12:14 UTC, nazarhussain requested changes

2021-10-19 12:14 UTC, nazarhussain commented on packages/web3-common/src/web3_base_provider.ts
> +		request: JsonRpcPayload<T2>,
I thought on it further and to align with the `EIP1339` it would be better to just use `JsonRpcRequest` here. User of the provider don't get into complexity of maintaining the request `id` and provider implementation should do it internally.

2021-10-20 06:22 UTC, Spacesai1or commented on packages/web3-providers-http/src/index.ts
> +	}
> The Provider is said to be "disconnected" when it cannot service RPC requests to any chain at all.

[Source](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#connectivity)

Which means we'd need to add logic to toggle the status depending on if requests can be made. Without making extra network calls to check the liveliness of the endpoint, we could only update when the user attempts to make a request. The status could easily be outdated if a successful request is made, but the endpoint immediately stops serving requests afterwards. Because of this, I don't think the status can be relied upon, and I question it's usefulness

2021-10-20 06:27 UTC, Spacesai1or commented on packages/web3-common/src/web3_base_provider.ts
> +		request: JsonRpcPayload<T2>,
The `1.x` implementation just passes whatever [payload](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-providers-http/src/index.js#L121) is given to it, so we should allow for the specification of `jsonrpc` and `id` to maintain backwards compatibility

2021-10-20 06:28 UTC, Spacesai1or commented on packages/web3-providers-http/src/index.ts
> +	}
However, based on [this](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-providers-http/src/index.js#L128), maybe we shouldn't throw errors and just do `// NO OP`

2021-10-20 17:48 UTC, nazarhussain commented on packages/web3-providers-http/src/index.ts
> +	}
My understanding to this is, the provider we have here is serving JSON-RPC over HTTP. And if we have a URL it means we can serve the JSON-RPC request. If there is an error during the request that should be treated as error.

2021-10-20 17:56 UTC, nazarhussain requested changes

2021-10-20 17:56 UTC, nazarhussain commented on packages/web3-common/src/web3_base_provider.ts
> +		request: JsonRpcPayload<T2>,
For this point I think we should break the 1.x compatibility. It will still not be a breaking change in terms of public exposed interfaces of the `web3` but will bring us more aligned with EIP1139.

The idea is the users of the providers would have to deal with less and less complexity. e.g. 

```ts
import {Web3HttpProvider} from 'web3-http-provider`;

const provider = new Web3HttpProvider('infura url');

await provivder.request({method: 'eth_getBlockByNumber', params: ['0x111']}
```

With this approach user will be less worried of maintaining the request id and json-rpc identifier and focus only on the request method he is interested in. 

What do you think?

2021-10-20 18:30 UTC, nazarhussain commented on packages/web3-common/src/web3_base_provider.ts
> +		request: JsonRpcPayload<T2>,
We decided to keep the `id` and `jsonrpc` identifier as optional for the `request`.

2021-10-20 18:30 UTC, nazarhussain approved these changes

2021-10-20 18:54 UTC, luu-alex approved these changes

2021-10-20 19:32 UTC, merged