web3 utils hashing encoding 4.x
ethereum/web3.js pull request #4471
Opened 2021-10-19 04:34 UTC by luu-alex

## Description
Closes: #4353
Functions apart of this:

   - sha3
   - sha3Raw
   - keccak256
   - soliditySha3 (based off of 1.x https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-utils/src/soliditySha3.js#L249)
   - soliditySha3Raw 
   - encodePacked 

## Changes in the soliditySha3, soliditySha3Raw, encodePacked:
 - We don't try to guess the type from the value given anymore (types must be specified)
 - Validate types of the values and throw errors if they don't match
 - address size does not default to the size of 32/40 bytes 
 - removed ufixedfixed type support, not fully supported by solidity (https://docs.soliditylang.org/en/latest/types.html#fixed-point-numbers)
 - types supported: string, bool/boolean, address, uint, int, int[], bytes

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2021-10-28 15:53 UTC, nazarhussain requested changes

2021-10-28 15:53 UTC, nazarhussain commented on packages/web3-utils/src/hash.ts
> +const SHA3_NULL = '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470';
I would prefer renaming this constant to `SHA3_EMPTY_BYTES` because that's what its belongs to. Current name implies that its the output of `keccak256(null)`, which its not.

2021-10-28 15:53 UTC, nazarhussain commented on packages/web3-utils/src/hash.ts
> +export const sha3 = (data: string): string | null => {
As per the usage of the code the input can be a lot of different type of values. 

```suggestion
export const sha3 = (data: Bytes): string | null => {
```

2021-10-28 15:53 UTC, nazarhussain commented on packages/web3-utils/src/types.ts
> +export type typedObject = {
Always use title case. 

```suggestion
export type TypedObject = {
```

2021-10-28 15:53 UTC, nazarhussain commented on packages/web3-utils/src/types.ts
> +export type typedObject2 = {
```suggestion
export type TypedObject2 = {
```

2021-10-28 15:53 UTC, nazarhussain commented on packages/web3-utils/test/unit/hash.test.ts
> +				// eslint-disable-next-line @typescript-eslint/no-magic-numbers
You can remove this line. We had disabled this globally for the tests.

2021-10-30 00:13 UTC, nazarhussain approved these changes

2021-11-02 02:43 UTC, spacesailor24 approved these changes

2021-11-02 05:05 UTC, merged