Create RequestManager and SubscriptionManager classes
ethereum/web3.js pull request #4478
Opened 2021-10-19 12:04 UTC by nazarhussain

## Description

Create the implementation of `RequestManager` and `SubscriptionManager`. 

Fixes #4429, #4430

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

2021-10-20 22:41 UTC, Spacesai1or commented on packages/web3-common/src/types.ts
> +export type JsonRpcResponse<R = JsonRpcResult, E = JsonRpcResult> =
We should formalize how we're going to specify these generics

Currently the rest of the repo uses `T, T2, etc.`, above you use:

```typescript
export class InvalidResponseError<ErrorType = unknown>
```

and now here you're using `R and E`.

My preference would to be explicit and use `ReturnType, ErrorType, etc.`

2021-10-20 22:54 UTC, Spacesai1or commented on packages/web3-common/src/web3_base_provider.ts
> +		return true;
Can you add documentation for what's going on here?

2021-10-21 00:01 UTC, Spacesai1or commented on packages/web3-core/src/web3_subscription_manager.ts
> +		const Klass = this.registeredSubscriptions[name];
`Klass`?

2021-10-23 01:41 UTC, Spacesai1or commented on packages/web3-core/src/web3_request_manager.ts
> +	public constructor(provider: Web3BaseProvider | string, net: Socket) {
Should `net` be optional, or `Socket` could be an additional type for `provider`, so:

```typescript
public constructor(provider: Web3BaseProvider | string | Socket) {
```

2021-10-23 01:57 UTC, Spacesai1or commented on packages/web3-core/src/web3_request_manager.ts
> +export class Web3RequestManager extends Web3EventEmitter<{
This should have a public `request` method, no?

2021-10-23 02:16 UTC, Spacesai1or commented on packages/web3-core/src/web3_request_manager.ts
> +	[key in Web3RequestManagerEvent]: SupportedProviders;
this resolves to type `any`

2021-10-25 21:45 UTC, nazarhussain commented on packages/web3-common/src/types.ts
> +export type JsonRpcResponse<R = JsonRpcResult, E = JsonRpcResult> =
I earlier used `T1`, `T2` which is common in TS space. But later I observed with complex generics its better to use full names, so why latest code is using the full name and will be using similar onward.

2021-10-25 21:48 UTC, nazarhussain commented on packages/web3-core/src/web3_subscription_manager.ts
> +		const Klass = this.registeredSubscriptions[name];
It returns the `classes` not the the `objects`, so why used this name.

2021-10-25 21:50 UTC, nazarhussain commented on packages/web3-core/src/web3_request_manager.ts
> +	public constructor(provider: Web3BaseProvider | string, net: Socket) {
To use existing code logic made it optional.

2021-10-25 21:50 UTC, nazarhussain commented on packages/web3-core/src/web3_request_manager.ts
> +export class Web3RequestManager extends Web3EventEmitter<{
For using existing name logic I used `send` if you prefer `request` we can rename it.

2021-10-25 21:55 UTC, nazarhussain commented on packages/web3-core/src/web3_request_manager.ts
> +	[key in Web3RequestManagerEvent]: SupportedProviders;
May be IDE is not loading up correctly. I tried in a test script and used tsc and it works fine.

2021-10-26 04:59 UTC, Spacesai1or commented on packages/web3-common/src/types.ts
> +export type JsonRpcResponse<R = JsonRpcResult, E = JsonRpcResult> =
Okay, we need to update all other instances to use full name as well - created [an issue](https://github.com/ChainSafe/web3.js/issues/4499) to track this

2021-10-26 05:06 UTC, Spacesai1or commented on packages/web3-core/src/web3_request_manager.ts
> +	public async send<ResultType, RequestType = unknown>(request: JsonRpcRequest<RequestType>) {
What about the [sendBatch](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-requestmanager/src/index.js#L198) method?

2021-10-26 12:50 UTC, nazarhussain commented on packages/web3-core/src/web3_request_manager.ts
> +	public async send<ResultType, RequestType = unknown>(request: JsonRpcRequest<RequestType>) {
We have a separate issue for this https://github.com/ChainSafe/web3.js/issues/4432

2021-10-26 20:10 UTC, Spacesai1or approved these changes

2021-10-26 20:31 UTC, luu-alex approved these changes

2021-10-27 15:44 UTC, jdevcs commented on packages/web3-common/src/web3_event_emitter.ts
> +	public on<K extends Web3EventKey<T>>(eventName: K, fn: Web3EventCallback<T[K]>) {
It should return Emitter for chained subscriptions. 

also there must be support of `once, removeListener, removeAllListeners`, ... etc 

IMO, there should be more control to user on EventEmitter for making it flexible, and we can do that by extending EventEmitter by Web3EventEmitter

2021-10-27 15:47 UTC, jdevcs commented on packages/web3-core/src/utils.ts
> +export const isSupportSubscriptions = (provider: SupportedProviders): boolean => {
`isSupportSubscriptions` should be enforced by baseProvider and implemented/handled in actual providers only. so I recommend to remove it from web3-core utils.

2021-10-27 16:06 UTC, jdevcs requested changes

2021-10-27 16:06 UTC, jdevcs commented on packages/web3-core/src/web3_config.ts
>  	private _config: ConfigOptions = {
should be named as eth1Config or `executionLayerConfig`

2021-10-27 16:12 UTC, jdevcs commented on packages/web3-core/src/web3_request_manager.ts
> +		}
if `provider` is not string but injected provider it must also set that.

2021-10-27 20:03 UTC, nazarhussain commented on packages/web3-common/src/web3_event_emitter.ts
> +	public on<K extends Web3EventKey<T>>(eventName: K, fn: Web3EventCallback<T[K]>) {
There should be lesser control for user and more for us. There should be more usability for the user in the provided API interfaces. 

e.g. For some of the use cases we don't want user to have `emit` on public interface (instance level) and we just want user to have event listener there. 

This above example provide the fact that we as library author need more control on what interfaces to make available for the users. So why we shouldn't extend from the `EventEmitter`, which will just expose unnecessary and sometime even vulnerabilities to the users.

2021-10-27 20:04 UTC, nazarhussain commented on packages/web3-core/src/utils.ts
> +export const isSupportSubscriptions = (provider: SupportedProviders): boolean => {
This logic is coupled with the `RequestManager` so why is part of `web3-core`. The `Web3BaseProvider` already have the public abstract interface for it. The function `isSupportSubscriptions` is using that interface to check.

2021-10-27 20:05 UTC, nazarhussain commented on packages/web3-core/src/web3_config.ts
>  	private _config: ConfigOptions = {
Its the the private variable, never been exposed to anywhere in the library, so no matter what name to use.

2021-10-28 12:56 UTC, jdevcs commented on packages/web3-core/src/web3_config.ts
>  	private _config: ConfigOptions = {
better readability

2021-10-28 12:57 UTC, jdevcs commented on packages/web3-common/src/web3_event_emitter.ts
> +	public on<K extends Web3EventKey<T>>(eventName: K, fn: Web3EventCallback<T[K]>) {
how will I as user can listen **once** for event, or remove listeners ?

2021-10-28 13:52 UTC, nazarhussain commented on packages/web3-common/src/web3_event_emitter.ts
> +	public on<K extends Web3EventKey<T>>(eventName: K, fn: Web3EventCallback<T[K]>) {
For removing listener we have `off` interface and I just added the support for `once` as well.

2021-10-28 13:53 UTC, nazarhussain commented on packages/web3-core/src/web3_config.ts
>  	private _config: ConfigOptions = {
I think as of now we have only this set of configuration so lest's just use `Web3Config` name as it is. Once we have some other set of configurations we can refactor.

2021-10-28 14:19 UTC, jdevcs approved these changes

2021-10-28 14:21 UTC, merged