init web3 eth accounts 4.x
ethereum/web3.js pull request #4496
Opened 2021-10-25 17:21 UTC by jdevcs

## Description
This PR have code for init of 4.x web3-eth-accounts package
and also minor fix in web3-core readme file

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

2021-10-25 17:43 UTC, luu-alex approved these changes

2021-10-25 18:06 UTC, Spacesai1or commented on packages/web3-core/README.md
> +# web3.js - Web3 Core
```suggestion
# web3.js - Web3 Eth Accounts
```

2021-10-25 18:06 UTC, nazarhussain approved these changes

2021-10-25 18:07 UTC, nazarhussain commented on packages/web3-core/README.md
> +# web3.js - Web3 Core
That seems to be correct change, its in the file `web3-core`

2021-10-25 18:20 UTC, Spacesai1or commented on packages/web3-eth-accounts/package.json
> +	"version": "4.0.0-alpha.1",
```suggestion
	"version": "4.0.0-alpha.0",
```

2021-10-25 18:21 UTC, Spacesai1or commented on packages/web3-core/README.md
> +# web3.js - Web3 Core
Oh you're right, but why is this file included in this PR?

2021-10-25 18:22 UTC, Spacesai1or requested changes
It doesn't matter that much, but why is `packages/web3-core/README.md` included in this PR? Also version number needs to be changed, as this package hasn't been released yet for `4.x`

2021-10-26 09:35 UTC, jdevcs commented on packages/web3-core/README.md
> +# web3.js - Web3 Core
Mentioned in desc: This PR have code for init of 4.x web3-eth-accounts package
and also minor fix in web3-core readme file.

This change is made in same PR instead of suggesting / opening another.

2021-10-26 18:07 UTC, Spacesai1or approved these changes

2021-10-27 09:02 UTC, merged