Add example import for package level types
ethereum/web3.js pull request #4611
Opened 2021-12-08 21:02 UTC by jgresham

I couldn't find an example import for package level types documented elsewhere

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2021-12-09 16:40 UTC, nazarhussain requested changes

2021-12-09 16:40 UTC, nazarhussain commented on README.md
> +import { BlockHeader, Block } from 'web3-eth' // ex. package types
I don't understand the reason or benefit of changing this example. If you think an example for other packages is good to have, then would suggest to create a separate example for it.

2021-12-09 16:41 UTC, nazarhussain commented
Hi @jgresham Thanks for contribution. I posted some feedback. In addition to it I suggest you to create an issue on Github repo and link your PR to it. Also create an entry to `CHANGELOG.md` specifying your PR.

2021-12-16 23:16 UTC, jgresham commented
@nazarhussain When I wanted to import the `Block` type from web3, I did not know where to import them from. I intuitively thought it would be `import { Block } from 'web3'` but that was not the case. Perhaps I am missing a tool which would have automatically found that it is `import { Block } from 'web3-eth'`.. but if this is not a common tool that users have installed, then I think it would benefit users to have this documented somewhere. If needed, where would you suggest it be documented?

2021-12-17 14:58 UTC, nazarhussain commented
@jgresham As we are focused on `4.x` rewrite which is done completely in Typescript. So you will be get more safe and more consistent developer experience with that release. For `1.x` seems mentioning it the README is fine.

2021-12-17 14:58 UTC, nazarhussain approved these changes

2022-01-06 18:17 UTC, luu-alex approved these changes

2022-01-21 12:09 UTC, merged