added webpack 5 create-react-app instructions
ethereum/web3.js pull request #4670
Opened 2022-01-06 18:09 UTC by luu-alex

Closes: #4659 #4173
## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2022-01-07 17:16 UTC, nazarhussain requested changes

2022-01-07 17:16 UTC, nazarhussain commented on README.md
> +If you are using create-react-app version >=5 you may run into issues building. This is because polyfills are not included in the latest version of create-react-app.
NodeJS polyfills.

2022-01-07 17:16 UTC, nazarhussain commented on README.md
> +};
I think we can do this with webpack ProviderPlugin. We don't need a separate script file.

2022-01-09 17:39 UTC, nazarhussain approved these changes

2022-01-10 13:20 UTC, jdevcs approved these changes

2022-01-10 18:40 UTC, merged