add: custom transaction polling interval (#4584)
ethereum/web3.js pull request #4672
Opened 2022-01-07 02:28 UTC by spacesailor24

Debugging failing Windows test

2022-01-07 09:38 UTC, nazarhussain approved these changes

2022-01-07 11:04 UTC, jdevcs commented on CHANGELOG.md
> +- `transactionPollingInterval` added to web3, contract and method constructor options. defaults to 1 second. (#4584)
1.7.0 is already frozen under 1.7.0-rc this change should be under future releases

2022-01-07 11:04 UTC, jdevcs commented on CHANGELOG.md
> +- `transactionPollingInterval` added to web3, contract and method constructor options. defaults to 1 second. (#4584)
1.7.0 is already frozen under 1.7.0-rc so this change should be under future release instead of 1.7.0

2022-01-07 11:09 UTC, jdevcs requested changes

2022-01-07 11:09 UTC, jdevcs commented on docs/web3-eth.rst
> +``number``: The current value of transactionPollingInterval (default: 1000)
I think this should have unit 

```suggestion
``number``: The current value of transactionPollingInterval (default: 1000ms)
```

2022-01-07 11:09 UTC, jdevcs commented on docs/web3-eth-contract.rst
> +``number``: The current value of transactionPollingInterval (default: 1000)
```suggestion
``number``: The current value of transactionPollingInterval (default: 1000ms)
```

2022-01-14 15:13 UTC, luu-alex approved these changes

2022-01-14 19:06 UTC, jdevcs approved these changes

2022-01-14 19:09 UTC, merged