Fix typos in REVIEW.md and TESTING.md
ethereum/web3.js pull request #4691
Opened 2022-01-11 16:21 UTC by myersg86

## Description

Fixes typographical errors in markdown files

REVIEW.md:10:  unneccessary -> unnecessary
REVIEW.md:23:  succesfully -> successfully
TESTING.md:55: programatically -> programmatically

## Type of change

Documentation - typofix

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2022-01-14 16:47 UTC, luu-alex commented
Hey! Thank you for this PR :) one last thing, can you update the [changelog](https://github.com/ChainSafe/web3.js/blob/1.x/CHANGELOG.md)

2022-01-17 13:55 UTC, jdevcs requested changes

2022-01-17 13:55 UTC, jdevcs commented on CHANGELOG.md
> + -  Fix typos in REVIEW.md and TESTING.md (#4691)
@myersg86 Could you make it under 1.7.1 instead of 1.7.0, Thanks

2022-01-18 07:04 UTC, nazarhussain approved these changes

2022-01-19 16:30 UTC, luu-alex approved these changes

2022-01-19 16:30 UTC, jdevcs approved these changes

2022-01-19 16:31 UTC, merged