ens registry abi - 4.x
ethereum/web3.js pull request #4700
Opened 2022-01-12 20:34 UTC by luu-alex

This PR only includes the registry ABI for ENS #4601

2022-01-17 13:27 UTC, jdevcs commented
Hi Alex, Could you check and fix, **Build / lint (pull_request)**

2022-01-18 16:07 UTC, luu-alex commented
@jdevcs  updated

2022-01-19 07:51 UTC, nazarhussain requested changes
Why we have to declare it in JS file and not TS? 

I would suggest to declare it as TS and `as const`

2022-01-19 17:02 UTC, nazarhussain approved these changes

2022-01-20 15:06 UTC, closed without merging