ENS ABI contract ReverseRegistrar and TestRegistrar
ethereum/web3.js pull request #4714
Opened 2022-01-18 18:43 UTC by luu-alex

closes:#4600
Feature parity with ENS for the ABI contract functions for 4.x rewrite
Includes:

https://github.com/ensdomains/ens/blob/master/contracts/ReverseRegistrar.sol
ReverseRegistrar Abi:
- claim
- claimWithResolver
- setName
- node
- defaultResolver

https://github.com/ensdomains/ens/blob/master/contracts/TestRegistrar.sol
TestRegistrar Abi:
- register
- expiryTimes

2022-01-19 17:03 UTC, nazarhussain requested changes

2022-01-19 17:03 UTC, nazarhussain commented on packages/web3-eth-ens/src/ABI/ReverseRegistrar.ts
> +const REVERSEREGISTRAR = [
Why such naming convention? Why not `REVERSE_REGISTRAR` or simply `rerverseRegistrar`?

2022-01-19 17:26 UTC, luu-alex commented on packages/web3-eth-ens/src/ABI/ReverseRegistrar.ts
> +const REVERSEREGISTRAR = [
I was following for what was done in 1.x but I'm not too sure if we are following a convention. It seems like upper case letters is widely used but either sounds fine to me, ill go with `REVERSE_REGISTRAR `

2022-01-20 08:49 UTC, nazarhussain approved these changes

2022-01-20 14:38 UTC, jdevcs reviewed
lgtm, 
could you also put links referring to solidity contract in comments?

2022-01-20 14:58 UTC, jdevcs approved these changes

2022-01-20 15:04 UTC, merged