Fix jsonrpc payload and response types (#4743)
ethereum/web3.js pull request #4761
Opened 2022-02-08 19:05 UTC by jdevcs

e2e_windows were not passing in [this](https://github.com/ChainSafe/web3.js/pull/4743) PR so opened current PR for checks  / fixes .
______________________________________
4743:
* Make JsonRpcPayload's `params` field optional

Currently jsonrpc.js uses `params: params || []` in the
`toPayload` function, so this type update makes the `params` field
optional to match.

* Fix JsonRpcResponse type

Update `id` to accept `string | number` - this now matches the
`isValidResponse` function in `jsonrpc.js`.

Update `error` to accept an object with optional `code`, `data`,
and non-optional `message` fields to more closely match the
[JSON RPC spec](https://www.jsonrpc.org/specification#error_object)
and the `ErrorResponse` function in `errors.js`.

* Remove errant spaces

* Add PR #443 to CHANGELOG

Co-authored-by: jdevcs <86780488+jdevcs@users.noreply.github.com>

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2022-02-08 20:20 UTC, luu-alex approved these changes

2022-02-09 12:13 UTC, nazarhussain approved these changes

2022-02-15 05:50 UTC, spacesailor24 requested changes
We've refrained from making any changes to 1.x's types because it's considered a breaking change for those using typescript

2022-03-10 16:31 UTC, davidmurdoch commented
@spacesailor24 The JSON RPC error property is 100% wrong in every case as is, so I think that should be fixed as no one can rely on that as it is, and if they somehow are, their runtime code is likely broken.

This is _technically_ not a breaking change in Web3's types, as it aligns it with runtime behavior, but for Ganache to have to make the change on our side in v7 it certainly would be breaking (and wrong).

Please reconsider merging this into 1.x.

2022-03-13 01:58 UTC, spacesailor24 commented
> @spacesailor24 The JSON RPC error property is 100% wrong in every case as is, so I think that should be fixed as no one can rely on that as it is, and if they somehow are, their runtime code is likely broken.
> 
> This is _technically_ not a breaking change in Web3's types, as it aligns it with runtime behavior, but for Ganache to have to make the change on our side in v7 it certainly would be breaking (and wrong).
> 
> Please reconsider merging this into 1.x.

@davidmurdoch Okay, yea that totally makes sense. We had a blanket policy of not making 1.x type changes, but I should've spent more time understanding this one - weird that the types were even written this way

2022-03-13 01:58 UTC, spacesailor24 approved these changes

2022-03-13 02:13 UTC, merged