Create the web3 package structure for 4.x
ethereum/web3.js pull request #4782
Opened 2022-02-16 11:07 UTC by nazarhussain

## Description

Create package skeleton for `web3`

Fixes #4679

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

2022-02-16 21:55 UTC, luu-alex approved these changes

2022-02-17 15:04 UTC, jdevcs requested changes

2022-02-17 15:04 UTC, jdevcs commented on packages/web3/README.md
> +This is a sub-package of [web3.js][repo].
```suggestion
This is the main package of [web3.js](https://github.com/ChainSafe/web3.js).
```

2022-02-17 15:04 UTC, jdevcs commented on packages/web3/package.json
> +	"license": "LGPL-3.0",
```suggestion
	"license": "LGPL-3.0",
	"keywords": [
        "Ethereum",
        "JavaScript",
        "API" ],
```

2022-02-17 15:04 UTC, jdevcs commented on packages/web3/package.json
> +	"repository": "https://github.com/ChainSafe/web3.js",
```suggestion
	"repository": "https://github.com/ChainSafe/web3.js",
	"engines": {
        "node": ">=12.0.0"
    },
    
    
```

2022-02-21 13:18 UTC, jdevcs approved these changes

2022-02-21 13:28 UTC, merged