`defaultTransactionBuilder` Refactors and Add Gas Pricing to `sendTransaction`
ethereum/web3.js pull request #4837
Opened 2022-03-10 07:53 UTC by spacesailor24

- `Web3ConfigOptions`'s `defaultBlock` type changed from `HexString` to `BlockNumberOrTag`
- Split `defaultTransactionBuilder` into several functions, some which are exported to be used elsewhere in the code
    - `getTransactionFrom`
    - `getTransactionNonce`
    - `getTransactionType`
    - `getTransactionGasPricing`
        - This was pulled into it's own file: `packages/web3-eth/src/utils/get_transaction_gas_pricing.ts` due to it's size
- Update `sendTransaction` (in `packages/web3-eth/src/rpc_method_wrappers.ts`) to fetch gas pricing (`gasPrice` or `maxPriorityFeePerGas` and `maxFeePerGas`) if not provided by user
- Add `options` object to `sendTransaction`, currently has one setting: `ignoreGasPricing`
    - `ignoreGasPricing = true` will not auto fill gas pricing as it always done (if not provided by user) in 1.x. Addresses issue #4509

2022-03-10 08:13 UTC, nazarhussain requested changes

2022-03-10 08:13 UTC, nazarhussain commented on packages/web3-eth/src/utils/transaction_builder.ts
> +};
Do we need to get transaction or account or address?

2022-03-10 08:24 UTC, nazarhussain requested changes

2022-03-10 08:24 UTC, nazarhussain commented on packages/web3-eth/src/utils/transaction_builder.ts
> +export const getTransactionFrom = (
```suggestion
export const getTransactionFromAddress = (
```

2022-03-10 08:25 UTC, nazarhussain approved these changes
Apart from that one comment, rest LGTM.

2022-03-11 03:20 UTC, luu-alex approved these changes

2022-03-11 07:17 UTC, merged