Junaid/errorhandling4583
ethereum/web3.js pull request #4847
Opened 2022-03-14 21:16 UTC by jdevcs

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2022-03-16 05:03 UTC, nazarhussain requested changes

2022-03-16 05:03 UTC, nazarhussain commented on packages/web3-eth/src/errors.ts
> +			).replace(/['"]+/g, ''),
I would suggest to move this logic of parsing data to string into `web3-utils` package and then use here.

2022-03-17 05:08 UTC, luu-alex approved these changes

2022-03-17 07:08 UTC, spacesailor24 requested changes, later dismissed
This `jsonStringify` shouldn't be applied to specific errors, but rather the [Web3Error](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-common/src/errors.ts#L57) class which our errors extend. In this way, the developer doesn't have to think about it every time they introduce a new error (possibly forgetting to do this, causing a runtime error)

I also wouldn't name this functionality `jsonStringify`, since `JSON.stringify` exists and this isn't just handling JSON. Perhaps we can just make a `toString` method that can handle BigInts, objects, Buffers, etc

2022-03-18 10:05 UTC, nazarhussain approved these changes

2022-03-18 10:06 UTC, nazarhussain commented
Apart from @spacesailor24  comment LGTM.

2022-03-18 19:41 UTC, avkos commented
> This `jsonStringify` shouldn't be applied to specific errors, but rather the [Web3Error](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-common/src/errors.ts#L57) class which our errors extend. In this way, the developer doesn't have to think about it every time they introduce a new error (possibly forgetting to do this, causing a runtime error)
> 
> I also wouldn't name this functionality `jsonStringify`, since `JSON.stringify` exists and this isn't just handling JSON. Perhaps we can just make a `toString` method that can handle BigInts, objects, Buffers, etc

yes. I also think we need to implement it inside the Web3Error class.

2022-03-18 19:42 UTC, avkos requested changes
yes. I also think we need to implement it inside the Web3Error class.

2022-03-21 20:06 UTC, jdevcs commented
> This `jsonStringify` shouldn't be applied to specific errors, but rather the [Web3Error](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-common/src/errors.ts#L57) class which our errors extend. In this way, the developer doesn't have to think about it every time they introduce a new error (possibly forgetting to do this, causing a runtime error)
> 
> I also wouldn't name this functionality `jsonStringify`, since `JSON.stringify` exists and this isn't just handling JSON. Perhaps we can just make a `toString` method that can handle BigInts, objects, Buffers, etc

[Web3Error](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-common/src/errors.ts#L57)  is already getting [string](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-common/src/errors.ts#L61) instead of `unknown` type and all of its sub classes are passing string, so no need of parsing that.

More good candidate of parsing `unknown` is [here](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-utils/src/errors.ts#L6), 

 I think this another [web3error](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-utils/src/errors.ts#L2) is created in utils package for avoiding cyclic dependency bw utils and common, but @spacesailor24 Why you used it in web3-eth package instead of web3-error from [common](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-common/src/errors.ts#L57), I think it should be changed in Eth.

2022-03-22 09:53 UTC, avkos approved these changes

2022-03-23 15:57 UTC, jdevcs commented
@spacesailor24

2022-03-23 17:46 UTC, spacesailor24 commented
> > This `jsonStringify` shouldn't be applied to specific errors, but rather the [Web3Error](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-common/src/errors.ts#L57) class which our errors extend. In this way, the developer doesn't have to think about it every time they introduce a new error (possibly forgetting to do this, causing a runtime error)
> > I also wouldn't name this functionality `jsonStringify`, since `JSON.stringify` exists and this isn't just handling JSON. Perhaps we can just make a `toString` method that can handle BigInts, objects, Buffers, etc
> 
> [Web3Error](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-common/src/errors.ts#L57) is already getting [string](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-common/src/errors.ts#L61) instead of `unknown` type and all of its sub classes are passing string, so no need of parsing that.
> 
> More good candidate of parsing `unknown` is [here](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-utils/src/errors.ts#L6),
> 
> I think this another [web3error](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-utils/src/errors.ts#L2) is created in utils package for avoiding cyclic dependency bw utils and common, but @spacesailor24 Why you used it in web3-eth package instead of web3-error from [common](https://github.com/ChainSafe/web3.js/blob/f71d2fe37cf2848d1368f902b376d5fa6cc96714/packages/web3-common/src/errors.ts#L57), I think it should be changed in Eth.

@jdevcs I didn't realize we had two different implementations of `Web3Error`, dependency cycle aside, this does not seem like the best approach and we should investigate only having one class for errors

I think you're right, `Web3Eth` should be using `Web3Error` from `web3-common` and just pass a formatted string. To do this though, we still require formatting potential `unknown` type values into a `string` to be used for the error message

2022-03-24 13:38 UTC, nikoulai approved these changes

2022-03-24 15:54 UTC, jdevcs commented
https://github.com/ChainSafe/web3.js/issues/4889

2022-03-24 15:55 UTC, merged