Fix confirmation check after transaction getting stuck in a loop in some situations
ethereum/web3.js pull request #4876
Opened 2022-03-21 18:06 UTC by Darkhogg

## Description

Sometimes, the checkConfirmation login became completely stuck and unable to exit properly, wasting a lot of CPU cycles and API calls on nothing.

I've seen this behaviour in situations where the generations of new blocks was slow (in which case polling kicks in and both polling and subscription remained working, but only one of them would ever finish) and when using `.once('confirmation')` on the result of a `sendSignedTransaction` call.

This PR fixes the afforementioned cases in the most simple way I came up with that doesn't break other stuff.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] I have selected the correct base branch.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
    - Honestly, I have no idea how to test this, it doesn't produce any internally visible anything
- [X] I ran `npm run test:unit` with success.
- [X] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [X] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [X] I have tested my code on the live network.
    - On rinkeby, where I actually had the problem (and the problem is gone)
- [x] I have checked the Deploy Preview and it looks correct.
- [X] I have updated the `CHANGELOG.md` file in the root folder.

2022-03-21 22:54 UTC, Darkhogg commented
Ok so apparently this also happens if you just... not subscribe to the `confirmation` event? I might spend some time tomorrow writing a proper set of test cases because I'm going insane right now.

2022-03-30 16:55 UTC, jdevcs commented
Thanks @Darkhogg did you get time of adding test and fixing merge conflicts.

2022-04-11 05:54 UTC, avkos approved these changes

2022-04-11 15:15 UTC, nazarhussain approved these changes

2022-04-11 15:16 UTC, nazarhussain requested changes
@Darkhogg Please convert the draft PR to ready and then request the request again.

2022-04-27 15:56 UTC, jdevcs commented on packages/web3-core-method/src/index.js
> +                    if (!canUnsubscribe || defer.eventEmitter.listeners('confirmation').length > 0) {
Pending items are ( tests cases and fixing merge conflicts ). There is no activity on this PR from contributor so closing. @Darkhogg feel free to reopen and fix issues in this PR when have time.

2022-04-27 15:57 UTC, closed without merging