4811/investigate eslint errors in web3 eth
ethereum/web3.js pull request #4893
Opened 2022-03-27 15:54 UTC by nikoulai

## Description

#4811 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2022-03-28 11:04 UTC, nikoulai commented
@spacesailor24 Tests seem to pass. What do you think?
(I opened a new PR because I had made a mistake in the name of my branch in the previous)

2022-03-29 11:02 UTC, avkos approved these changes

2022-03-29 12:19 UTC, nazarhussain requested changes
@nikoulai  Please change the base branch of this PR to the one you started with. Currently it contains a lot of extra commits and unable to identify change related to this PR.

2022-04-08 04:45 UTC, spacesailor24 approved these changes

2022-04-08 09:14 UTC, luu-alex approved these changes

2022-04-11 15:14 UTC, nazarhussain approved these changes
Please resolve the conflicts, rest seems good.

2022-04-12 12:01 UTC, jdevcs approved these changes

2022-04-12 12:08 UTC, merged