Update index.d.ts
ethereum/web3.js pull request #4955
Opened 2022-04-20 15:42 UTC by bigbizze

the changed callback type returns an array of event data rather than an object of one event's data: https://www.quicknode.com/docs/ethereum/eth_getLogs

2022-04-25 15:04 UTC, jdevcs reviewed
@bigbizze changelog update is missing.

2022-04-25 17:12 UTC, avkos approved these changes

2022-04-26 07:07 UTC, avkos approved these changes

2022-04-26 10:24 UTC, nazarhussain approved these changes

2022-04-26 10:27 UTC, nazarhussain requested changes
@bigbizze Please add details to the CHANGELOG.md rest seems good.

2022-04-26 13:38 UTC, avkos approved these changes

2022-05-04 09:54 UTC, nazarhussain commented
@bigbizze Did you get chance to look into this PR. Please add the CHANGELOG.md entry so we can get this PR ready to merge.

2022-05-17 11:51 UTC, nazarhussain approved these changes

2022-07-18 08:40 UTC, merged