web3: added option to enable/disable autoconnect
ethereum/web3.js pull request #5016
Opened 2022-05-10 09:26 UTC by jagpreetsinghsasan

## Description
Added a boolean to enable/disable autoconnect

Fixes #4957

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2022-05-24 16:54 UTC, jdevcs requested changes

2022-05-24 16:54 UTC, jdevcs commented on packages/web3-providers-ws/src/index.ts
> +		autoConnect?: boolean,
There is already [autoConnect](https://github.com/ChainSafe/web3.js/blob/82574a2587810f9bea26ba65da48fe667162e573/packages/web3-providers-ws/src/types.ts#L21) in `reconnectOptions` 

```suggestion
		
```

2022-05-24 16:55 UTC, jdevcs commented on packages/web3-providers-ws/src/index.ts
> +			this.connect();
This is for first time connection , not for re connect so what is need of adding this check here?

2022-05-24 16:56 UTC, jdevcs commented on packages/web3-providers-ws/src/index.ts
> +		this.connect();
Validate will be called before init so why this connect is added here?

2022-06-02 05:12 UTC, jagpreetsinghsasan commented on packages/web3-providers-ws/src/index.ts
> +		autoConnect?: boolean,
Oh, maybe I wasn't using the version of web3 which has this.
Closing the PR as the feature already exists,

2022-06-02 05:12 UTC, closed without merging