Web3.js Woodpile
ethereum/web3.js pull request #5061
Opened 2022-05-23 00:01 UTC by Woodpile37

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2022-06-09 13:58 UTC, jdevcs requested changes

2022-06-09 13:58 UTC, jdevcs commented on packages/web3-eth-abi/package.json
> +        "@ethersproject/abi": "5.6.1",
@Woodpile37 There are merge conflicts could you fix those, and @ethersproject/abi package is updated in another PR https://github.com/ChainSafe/web3.js/blob/23e3045cdd54421ede10b3633d39e1a5576ee790/packages/web3-eth-abi/package.json#L17 so we can remove this changes of package and package lock in this PR.

2022-06-09 19:22 UTC, Woodpile37 reviewed
Hey

2022-06-16 11:10 UTC, Woodpile37 commented
Thank you

2022-06-16 11:11 UTC, Woodpile37 commented on packages/web3-eth-abi/package.json
> +        "@ethersproject/abi": "5.6.1",
🤘

2022-06-22 15:43 UTC, nazarhussain requested changes
@Woodpile37 Please consider these points: 

1. Resolve the conflicts 
2. Remove the `package-lock.json` from your PR, as we will generate the file internally. 
3. Add entry to `CHANGELOG.md` to document what's been updated in this PR.

2022-06-22 18:06 UTC, nazarhussain commented
@Woodpile37 Also update the title of the PR as well.

2022-06-30 08:31 UTC, Woodpile37 reviewed
Thank you

2022-07-06 19:03 UTC, jdevcs requested changes
@Woodpile37  ethersproject lib is already updated in another PR https://github.com/ChainSafe/web3.js/blob/35d8f7f76ca9412b714775cf15a2c1d57001020b/packages/web3-eth-abi/package.json#L17  , so could you remove changes in package and package lock files.

2022-07-07 03:50 UTC, Woodpile37 reviewed
Approve

2022-09-20 15:51 UTC, avkos requested changes
@Woodpile37 please remove package.json changes.
```"@ethersproject/abi": "5.6.2",```

2022-10-07 14:02 UTC, jdevcs reviewed
This PR is waiting for response from long time, so I am closing this PR. Feel free to come back and reopen.

2022-10-07 14:02 UTC, closed without merging