:memo: Add TSDoc and Docusaurus support
ethereum/web3.js pull request #5062
Opened 2022-05-23 15:33 UTC by nazarhussain

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` with success.
- [x] I have tested the built `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

2022-05-30 12:07 UTC, nikoulai commented
When I run `yarn start` inside `docs` directory, I get 
```
[INFO] Starting the development server...
[ERROR] Loading of version failed for version current
[ERROR] Error: Invalid sidebar file at "sidebars.js".
These sidebar document ids do not exist:
- api/web3
...
```
If I remove items in sidebars.js  it runs successfully. Is there any error or it's on my side?
(I have run ./scripts/build_api_docs.js and yarn previously)

2022-05-30 14:39 UTC, nazarhussain commented
@nikoulai Please make sure you are running with the latest branch. I just checked out locally and see following output. 

```
[INFO] Starting the development server...
Info: Loaded plugin typedoc-monorepo-link-types
Info: Loaded plugin typedoc-plugin-extras
Info: Loaded plugin @droppedcode/typedoc-plugin-relative-includes
Info: Loaded plugin typedoc-plugin-mdn-links
Info: Documentation generated at ./docs/api

[SUCCESS] Docusaurus website is running at http://localhost:3000/.
```

2022-05-30 17:27 UTC, nikoulai approved these changes

2022-05-30 20:35 UTC, jdevcs requested changes

2022-05-30 20:35 UTC, jdevcs commented on docs/docusaurus.config.js
> +	url: 'https://docs.web3js.com',
```suggestion
	url: 'https://docs.web3js.org',
```

2022-05-30 20:35 UTC, jdevcs commented on docs/docusaurus.config.js
> +								href: 'https://discord.gg/uH8JRuv5',
```suggestion
								href: 'https://discord.com/invite/pb3U4zE8ca',
```

2022-05-30 20:35 UTC, jdevcs commented on docs/docusaurus.config.js
> +				copyright: `Copyright © ${new Date().getFullYear()} Web3.js, Inc. Built with Docusaurus.`,
```suggestion
				copyright: `Copyright © ${new Date().getFullYear()} Web3.js . Built with Docusaurus.`,
```

2022-05-30 20:58 UTC, jdevcs commented on docs/docusaurus.config.js
> +								href: 'https://stackoverflow.com/questions/tagged/web3.js',
this results in: 
```
Questions tagged [web3.js]
0 questions
```

2022-05-30 20:59 UTC, jdevcs commented on docs/docusaurus.config.js
> +								href: 'https://discord.gg/uH8JRuv5',
this was resulting in invalid link

2022-05-30 21:08 UTC, jdevcs commented
LGTM, except some minor changes required

2022-05-31 12:56 UTC, nazarhussain commented on docs/docusaurus.config.js
> +								href: 'https://stackoverflow.com/questions/tagged/web3.js',
Fixed the link.

2022-05-31 13:02 UTC, jdevcs approved these changes

2022-05-31 14:19 UTC, merged