:art: Improve the nullish value usage around the codebase
ethereum/web3.js pull request #5095
Opened 2022-06-01 19:58 UTC by nazarhussain

## Description

Update all the usage of `nullish` values around the codebase as per the guideline in the issue. 

Fixes #5094

## Type of change

- [ x] Improvement 

## Checklist:

- [x ] I have selected the correct base branch.
- [x I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [x ] Any dependent changes have been merged and published in downstream modules.
- [ x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` with success.
- [x] I have tested the built `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

2022-06-02 13:41 UTC, nazarhussain commented
The changes related to doc comments blocks appears because of running `yarn lint:fix`

2022-06-02 13:50 UTC, avkos approved these changes

2022-06-02 21:19 UTC, jdevcs requested changes
LGTM, only minor changes required.

2022-06-02 21:19 UTC, jdevcs commented on packages/web3-errors/src/web3_error_base.ts
> +		if (value === null) return 'undefined';
```suggestion
		// Using "null" value intentionally for validation
		// eslint-disable-next-line no-null/no-null
		if (value === null || value === undefined ) return 'undefined';
```

2022-06-02 21:19 UTC, jdevcs commented on packages/web3-eth/src/types.ts
> +	readonly contractAddress: Address;
```suggestion
	readonly contractAddress?: Address;
```

2022-06-02 21:20 UTC, jdevcs commented
and also some tests are failing so needs to be fixed in this PR.

2022-06-03 19:40 UTC, jdevcs approved these changes

2022-06-03 19:52 UTC, luu-alex approved these changes

2022-06-07 15:20 UTC, merged