Updates on `README.md` Format
ethereum/web3.js pull request #5115
Opened 2022-06-08 10:46 UTC by MujeebullahKalwar

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

## Type of change

Small Changes in Readme File

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2022-06-09 13:45 UTC, jdevcs approved these changes

2022-06-22 18:23 UTC, nazarhussain approved these changes

2022-06-22 18:23 UTC, nazarhussain requested changes
@MujeebullahKalwar Please add an entry to CHANGELOG.me for the relevant change.

2022-06-22 18:53 UTC, mujeeb-kalwar commented
> @MujeebullahKalwar Please add an entry to CHANGELOG.me for the relevant change.

Added

2022-06-22 20:41 UTC, nazarhussain approved these changes

2022-06-28 12:04 UTC, merged