add similar library for swift language
ethereum/web3.js pull request #5135
Opened 2022-06-14 12:25 UTC by amirhossein7

## Description

Add similar library for swift language & update README.md file.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2022-06-16 09:39 UTC, nikoulai approved these changes

2022-06-22 18:30 UTC, nazarhussain requested changes
@amirhossein7 Is this the only library available for Swift. Can you please list down top available swift packages so we can discuss which one to be listed here.

2022-06-23 20:06 UTC, amirhossein7 commented
@nazarhussain swift packages repositories for web3

1. [skywinder](https://github.com/skywinder/web3swift)
2. [Boilertalk](https://github.com/Boilertalk/Web3.swift)
3. [MercuryProtocol](https://github.com/MercuryProtocol/web3.swift)
4. [zeriontech](https://github.com/zeriontech/Web3Swift)

2022-07-18 08:34 UTC, nazarhussain approved these changes

2022-09-06 22:08 UTC, avkos approved these changes

2023-02-21 17:27 UTC, closed without merging