Incompatible return types for 4.x implementations
ethereum/web3.js pull request #5205
Opened 2022-07-05 12:06 UTC by nikoulai

## Description

#5126 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

2022-07-06 18:24 UTC, jdevcs requested changes

2022-07-06 18:24 UTC, jdevcs commented on packages/web3-eth/src/web3_eth.ts
> +		if (!response) throw new Error('Transaction not found!');
I think we should use consistent approach for known errors in 4.x, like https://github.com/ChainSafe/web3.js/blob/e6a9aea25d3ce808f9a1cab4a26164366b68d3f4/packages/web3-errors/src/errors/transaction_errors.ts#L122   so could you add some thing like `TransactionNotFound` new error.

2022-07-06 18:24 UTC, jdevcs commented on packages/web3-eth/src/web3_eth.ts
> +		if (!response) throw new Error('Transaction not found!');
Same here use Web3Errors

2022-07-07 08:30 UTC, nazarhussain approved these changes
Apart from @jdevcs comments, looks good to me.

2022-07-07 11:46 UTC, jdevcs approved these changes

2022-07-07 12:03 UTC, merged