Upgrade ethereum-cryptography to 1.0
ethereum/web3.js pull request #5211
Opened 2022-07-05 20:16 UTC by nazarhussain

## Description

Fixes #5122

## Type of change

- [x] Upgrades

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` with success.
- [x] I have tested the built `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

2022-07-06 12:50 UTC, nikoulai approved these changes

2022-07-06 12:50 UTC, nikoulai commented on packages/web3-eth-accounts/test/fixtures/account.ts
> +	// [
Why we need to comment these ?

2022-07-06 16:59 UTC, jdevcs requested changes

2022-07-06 16:59 UTC, jdevcs commented on packages/web3-eth-accounts/src/account.ts
> +		der: false,
```suggestion
		recovered: true, // makes signatures compatible with libsecp256k1
		der: false, //returned signature should be in DER format ( non compact )
```

2022-07-06 17:47 UTC, jdevcs requested changes

2022-07-06 17:47 UTC, jdevcs commented on packages/web3-eth-accounts/test/fixtures/account.ts
> +];
```suggestion
['','0x5f35dce98ba4fba25530a026ed80b2cecdaa31091ba4958b99b52ea1d068adad']
];
```

good to add edge case

2022-07-06 17:47 UTC, jdevcs commented on packages/web3-eth-accounts/test/fixtures/account.ts
> +	],
remove duplicate test data here

2022-07-06 18:09 UTC, jdevcs commented on packages/web3-eth-accounts/src/account.ts
> +	return sha3Raw(ethMessage);
```suggestion
	return sha3Raw(ethMessage);  // using keccak in web3-utils.sha3Raw instead of SHA3 (NIST Standard) as both are different
```

2022-07-06 18:09 UTC, jdevcs commented on packages/web3-eth-accounts/src/account.ts
> +	const txHash = sha3Raw(rawTx);
```suggestion
	const txHash = sha3Raw(rawTx); // using keccak in web3-utils.sha3Raw instead of SHA3 (NIST Standard) as both are different
```

2022-07-07 10:12 UTC, nazarhussain commented on packages/web3-eth-accounts/test/fixtures/account.ts
> +	// [
Forget to uncomment. Fixed it.

2022-07-07 11:39 UTC, jdevcs approved these changes

2022-07-07 15:35 UTC, luu-alex approved these changes

2022-07-07 16:02 UTC, merged