:art: Improve some conventions to be more easier projects migrations for 4.x
ethereum/web3.js pull request #5225
Opened 2022-07-08 19:06 UTC by nazarhussain

## Description

While migrating Truffle to 4.x I found following changes will make it easier for projects to migrate. 
- [x] Improvements

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` with success.
- [x] I have tested the built `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

2022-07-08 19:08 UTC, nazarhussain commented on packages/web3-eth/package.json
> +	"version": "4.0.0-alpha.2",
The version `4.0.0-alpha.1` is already published for this package.

2022-07-11 12:45 UTC, avkos requested changes
looks good. Great job! need to fix tests

2022-07-12 15:44 UTC, nikoulai approved these changes

2022-07-13 11:52 UTC, avkos approved these changes

2022-07-13 12:21 UTC, merged