Return Subscription object without await
ethereum/web3.js pull request #5226
Opened 2022-07-11 13:10 UTC by nikoulai

## Description

Fixes #5203

2022-07-12 19:30 UTC, luu-alex approved these changes

2022-07-13 10:50 UTC, nazarhussain requested changes

2022-07-13 10:50 UTC, nazarhussain commented on packages/web3-eth-contract/src/contract.ts
> +			});
I would suggest to create an `error` event and `emit` the error on `sub` object in this particular case.

2022-07-13 15:34 UTC, jdevcs approved these changes
apart from Nazar comments LGTM

2022-07-14 08:45 UTC, avkos approved these changes

2022-07-14 13:58 UTC, nazarhussain approved these changes

2022-07-14 14:06 UTC, merged