Enable subscribing to `error` event at `WebSocketProvider` underlying connection
ethereum/web3.js pull request #5333
Opened 2022-08-10 19:20 UTC by Muhammad-Altabba

## Description
Implementation of #(https://github.com/ChainSafe/web3.js/issues/5330)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

2022-08-11 09:06 UTC, avkos approved these changes

2022-08-11 09:08 UTC, avkos requested changes
Great job! 
just need to fix e2e tests

2022-08-15 11:01 UTC, avkos approved these changes

2022-08-16 11:14 UTC, jdevcs requested changes

2022-08-16 11:14 UTC, jdevcs commented on packages/web3-providers-ws/src/index.ts
> +			console.error(error);
Instead of console.error we should use same mechanism to notify user if any user is relying on error event. 
```suggestion
			this._wsEventEmitter.emit('error', error);
```

2022-08-16 16:20 UTC, Muhammad-Altabba commented on packages/web3-providers-ws/src/index.ts
> +			console.error(error);
Yes, but the point is that error is not in the underlying connection. So, it should not be fired in the `error` event I thought. However, I thought about it in a different way now and enhanced the code even more :) please check now...

2022-08-17 08:28 UTC, jdevcs approved these changes

2022-08-17 08:59 UTC, merged