Black box tests
ethereum/web3.js pull request #5353
Opened 2022-08-16 21:21 UTC by spacesailor24

supersedes #5280

2022-08-22 17:35 UTC, spacesailor24 commented on packages/web3/test/black_box/test/web3-eth-accounts/hashMessage.test.ts
> +jest.setTimeout(15000);
For only this test and `packages/web3/test/black_box/test/web3-eth-accounts/create.test.ts`, the `if (isWs) await closeOpenConnection(web3);` in `afterAll` takes longer to complete and surpasses the default timeout for Jest

2022-08-22 19:36 UTC, spacesailor24 commented on packages/web3/test/black_box/package.json
> +		"test:infura:ws": "WEB3_SYSTEM_TEST_BACKEND=infura jest"
These should use already set ENVs instead of setting it here

2022-08-23 12:05 UTC, jdevcs commented on .github/workflows/build.yml
> +  black-box:
It should be invoked on **tag** push and **release branch** only for saving time in normal PRs.

2022-08-23 12:32 UTC, jdevcs requested changes
lgtm, except some minor changes.

2022-08-23 12:32 UTC, jdevcs commented on .github/workflows/build.yml
> +          backend: ['ganache', 'geth', 'infura']
We already have multiple eth clients tests in e2e so for blackbox we can only test on one eth client and or Infura in github actions,  ( and should keep other Eth clients blackbox tests in scripts for local testing. )

2022-08-23 12:32 UTC, jdevcs commented on packages/web3/src/version.ts
> +/* eslint-disable header/header */ export const Web3PkgInfo = { version: '4.0.0-alpha.0' };
Its auto updated by reading https://github.com/ChainSafe/web3.js/blob/7a55b62bfa1c34b78a2014cba97e2e02dff353f9/packages/web3/package.json#L3 so web3 package;s package.json should also be updated

2022-08-23 12:32 UTC, jdevcs commented on packages/web3/test/black_box/package.json
> +	"license": "MIT",
license should be same as root package.json

2022-08-23 12:32 UTC, jdevcs commented on scripts/verdaccio.sh
> +        --registry http://localhost:4873 \
We are using local registry here but an extra step to avoid risk , 
add some tag other then default `latest` , may be `alpha` or `rc`

2022-08-23 16:43 UTC, nikoulai approved these changes

2022-08-23 18:24 UTC, jdevcs approved these changes

2022-08-23 18:35 UTC, luu-alex approved these changes

2022-08-24 02:38 UTC, merged