Add console warn for empty web3js construction
ethereum/web3.js pull request #5392
Opened 2022-08-29 14:14 UTC by nikoulai

## Description

#4985 

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

2022-08-29 16:13 UTC, avkos approved these changes

2022-08-30 16:04 UTC, jdevcs requested changes

2022-08-30 16:04 UTC, jdevcs commented on packages/web3/src/web3.ts
> +				'NOTE: web3.js is running in dev mode, without provider. You need to pass a provider in order to interact with the network!',
```suggestion
				'NOTE: web3.js is running without provider. You need to pass a provider in order to interact with the network!',
```

2022-08-30 18:10 UTC, jdevcs approved these changes

2022-08-30 19:35 UTC, merged