4.x info messages in 1.x
ethereum/web3.js pull request #5412
Opened 2022-09-01 20:19 UTC by jdevcs

## Description

https://github.com/ChainSafe/web3.js/issues/5411

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

2022-09-02 22:57 UTC, avkos commented on packages/web3/README.md
> +[deps-dev-url]: https://david-dm.org/ethereum/web3.js/1.x?type=dev&path=packages/web3
this link returns 504 `https://david-dm.org/ethereum/web3.js/1.x?type=dev&path=packages/web3`

2022-09-02 22:59 UTC, avkos requested changes
It will be great to fix not working links

2022-09-06 11:08 UTC, jdevcs commented
> It will be great to fix not working links

removed , also added 
![image](https://user-images.githubusercontent.com/86780488/188620866-810dab19-1388-4af5-bacd-b4a588a4fd8b.png)

2022-09-06 15:51 UTC, avkos approved these changes

2022-09-06 16:01 UTC, nikoulai approved these changes

2022-09-07 06:07 UTC, luu-alex commented on README.md
> +#####  [Web3.js 4.x][4x-release] has been release. Checkout 4.x [API documentation and migration guide][4xdoc] for testing, early feedback and contributions.
```suggestion
#####  [Web3.js 4.x][4x-release] has been released. Checkout 4.x [API documentation and migration guide][4xdoc] for testing, early feedback and contributions. 
```

2022-09-07 06:08 UTC, luu-alex commented on docs/index.rst
> +.. note:: `Web3.js 4.x <https://github.com/ChainSafe/web3.js/releases/tag/v4.0.0-alpha.0>`_ has been release. Checkout 4.x `API documentation and migration guide <https://docs.web3js.org/>`_ for test
```suggestion
.. note:: `Web3.js 4.x <https://github.com/ChainSafe/web3.js/releases/tag/v4.0.0-alpha.0>`_ has been released. Checkout 4.x `API documentation and migration guide <https://docs.web3js.org/>`_ for testing, early feedback and contributions. 
```

2022-09-07 06:09 UTC, luu-alex commented on packages/web3/README.md
> +#####  [Web3.js 4.x][4x-release] has been release. Checkout 4.x [API documentation and migration guide][4xdoc] for testing, early feedback and contributions.
```suggestion
#####  [Web3.js 4.x][4x-release] has been released. Checkout 4.x [API documentation and migration guide][4xdoc] for testing, early feedback and contributions. 
```

2022-09-07 06:10 UTC, luu-alex commented
just a small comment, otherwise lgtm

2022-09-07 06:10 UTC, luu-alex approved these changes

2022-09-07 12:01 UTC, merged