fix sync subscription
ethereum/web3.js pull request #5414
Opened 2022-09-03 01:53 UTC by avkos

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

2022-09-06 12:13 UTC, jdevcs requested changes

2022-09-06 12:13 UTC, jdevcs commented on packages/web3-eth/src/web3_subscriptions.ts
> +						: data.status.startingBlock,
Should this be?
```suggestion
						: data.status.currentBlock,
```

2022-09-06 18:22 UTC, jdevcs approved these changes

2022-09-08 11:05 UTC, Muhammad-Altabba reviewed
Looks good.
However, I just have a tiny question and a small suggestion.

2022-09-08 11:05 UTC, Muhammad-Altabba commented on packages/web3-eth/src/web3_subscriptions.ts
> +			};
This is good. However, maybe we can write it as the following suggestion and so it will be dynamic with no need to update if a new property has been added later:
```suggestion
            // Uncapitylize the first letter in the properties' names (for example: data.status.StartingBlock becomes data.status.startingBlock)
			const mappedData: SyncOutput = Object.fromEntries(Object.entries(data.status).map(([ key, value ]) => [key.charAt(0).toLowerCase()+key.substring(1), value]))
```
The above code was inspired by: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries#object_transformations
You can try it here: https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCmBbADjAvDA3gKBnmAylAIYBOUAlmAOYBCANiMANYBcMADADS74DCAV1Kl4YKAyZtOPfDAASFagAt40CS3bdeeANJgQAdzBFiCCJpn4ACgPr14AExNmL2AL7ZQkEPYB0jagAKbRgAeQAjACt4YChfADNSEEQAUTFSClVAiOjY31EoDKyEFABKX0RiZEDAgG0YZngATy4YADdiegF4GABdUvQAPhhaxqbfYCUyAEEoQI5yqBAAGUN4Uj5iCHhA0oBqMd8IAXDoDJpAgEZS1o6u+H7SkNKgA

You may like to put this in a helper function and call it here if you think this would be needed later...

Thanks,

2022-09-08 11:05 UTC, Muhammad-Altabba commented on packages/web3-eth/src/web3_subscriptions.ts
> +			this.emit('changed', data);
So no need to emit the 'data' event, if it is boolean?

2022-09-08 20:01 UTC, avkos commented on packages/web3-eth/src/web3_subscriptions.ts
> +			};
Good idea. Thx. fixed

2022-09-08 20:02 UTC, avkos commented on packages/web3-eth/src/web3_subscriptions.ts
> +			this.emit('changed', data);
Looks like we do not have data to emit. that's why only changed event

2022-09-09 10:10 UTC, Muhammad-Altabba commented on packages/web3-eth/src/web3_subscriptions.ts
> +			};
Thanks Oleksii,

2022-09-09 11:59 UTC, luu-alex approved these changes

2022-09-09 15:13 UTC, Muhammad-Altabba approved these changes

2022-09-09 15:21 UTC, merged