Add tests
ethereum/web3.js pull request #5457
Opened 2022-09-19 13:28 UTC by nikoulai

## Description

Web3 net system tests
#5042 

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

2022-09-19 20:06 UTC, avkos approved these changes

2022-09-20 09:36 UTC, Muhammad-Altabba commented
Hello @nikoulai,
Kindly check the error in `Build / Integration IPC `. As I think this error does not exist currently on the 4.x branch:
```
web3-net:   ● Web3 net › should be able to get id
web3-net:     expect(received).toBe(expected) // Object.is equality
web3-net:     Expected: 1111n
web3-net:     Received: 1337n
web3-net:       40 | 	it('should be able to get id', async () => {
web3-net:       41 | 		const networkId = await web3Net.getId();
web3-net:     > 42 | 		expect(networkId).toBe(BigInt(1111));
web3-net:          | 		                  ^
web3-net:       43 | 	});
web3-net:       44 |
web3-net:       45 | 	it('should be able to listen', async () => {
web3-net:       at test/integration/web3_net.test.ts:42:21
web3-net:       at fulfilled (test/integration/web3_net.test.ts:21:58)
```

2022-09-20 09:46 UTC, Muhammad-Altabba requested changes
Looks good,
Just fix the related issues in the Pipeline, please.

2022-09-21 14:23 UTC, jdevcs approved these changes

2022-09-26 09:14 UTC, Muhammad-Altabba approved these changes

2022-09-27 12:43 UTC, merged