Correct links to packages info at v4 website
ethereum/web3.js pull request #5471
Opened 2022-09-25 19:49 UTC by ndrozd

## Description

Replaced wrong links to correct ones pointing to v4 website.

Fixes #5405

## Type of change

- [+] Bug fix (non-breaking change which fixes an issue)

## Checklist for 1.x:

- [+] I have selected the correct base branch.
- [+] I have performed a self-review of my own code.
- [+] I have commented my code, particularly in hard-to-understand areas.
- [+] I have made corresponding changes to the documentation.
- [+] My changes generate no new warnings.
- [+] Any dependent changes have been merged and published in downstream modules.
- [+] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [+] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [+] I ran `npm run build` with success.
- [+] I have tested the built `dist/web3.min.js` in a browser.
- [+] I have tested my code on the live network.
- [+] I have checked the Deploy Preview and it looks correct.
- [+] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [+] I have selected the correct 4.x base branch.
- [+] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [+] I have performed a self-review of my own code
- [+] I have commented my code, particularly in hard-to-understand areas.
- [+] I have added any required tests for the changes I made 
- [+] I have made corresponding changes to the documentation
- [+] Any dependent changes have been merged and published in downstream modules.
- [+] I ran `yarn` successfully
- [+] I ran `yarn lint` successfully
- [+] I ran `yarn build:web` successfully
- [+] I ran `yarn test:unit` successfully
- [+] I ran `yarn test:integration` successfully
- [+] I ran `compile:contracts` successfully
- [+] I have tested my code.
- [+] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

2022-09-26 16:25 UTC, jdevcs requested changes
@ndrozd Thanks for your contribution, need a change in your PR.

2022-09-26 16:25 UTC, jdevcs commented on README.md
> +| [web3-eth-tx](https://github.com/ChainSafe/web3.js/tree/4.x/packages/web3-eth-tx)                 | [![npm](https://img.shields.io/npm/v/web3)](https://www.npmjs.com/package/web3-eth-tx)         |
we dnt have eth-tx package so this line should be removed: 
![image](https://user-images.githubusercontent.com/86780488/192330094-0d0ea773-4aac-4e1c-b485-0e93c4169535.png)

2022-09-26 19:03 UTC, ndrozd commented
@jdevcs done

2022-09-27 12:34 UTC, jdevcs approved these changes

2022-09-27 21:09 UTC, Muhammad-Altabba approved these changes
Thanks for your contribution.

2022-09-28 04:56 UTC, luu-alex approved these changes

2022-10-06 14:54 UTC, jdevcs commented
@ndrozd The base branch requires all commits to be signed.

2022-10-09 19:49 UTC, ndrozd commented
Sorry I don't get what's my action item here

2022-10-09 21:42 UTC, luu-alex commented
@ndrozd to contribute, your commits need to be verified. https://github.blog/changelog/2022-08-23-ssh-commit-verification-now-supported/

2022-10-20 21:52 UTC, avkos approved these changes

2022-11-03 03:47 UTC, ndrozd commented
Well it seems like I've messed something up while signing my prev commits....

2022-11-03 04:05 UTC, luu-alex commented
If it makes it easier, first verify your commits and then you can create a new branch and do the exact same commits

2022-11-03 11:38 UTC, ndrozd commented
It seems like reader file is totally different now anyway

2022-11-04 19:41 UTC, closed without merging