Emit past contract events based on `fromblock
ethereum/web3.js pull request #5472
Opened 2022-09-26 01:07 UTC by alexmylonas

## Description

This PR address the bug described in #5201 where past contact events wouldn't be fetched when `fromBlock` property was passed. 

This change checks for the existence of that property, call past events and emits them.

Fixes #5201 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 4.x:

- [x] I have selected the correct 4.x base branch.
- [x] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `yarn` successfully
- [x] I ran `yarn lint` successfully
- [x] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [x] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

2022-09-27 12:31 UTC, jdevcs reviewed
@alexmylonas Thanks for your contribution. 

CI has problem including test added in this PR https://github.com/web3/web3.js/actions/runs/3124396655/jobs/5067748417#step:4:198 so some one from our team will fix other tests and after that you can rebase your branch.

2022-10-20 22:19 UTC, avkos requested changes, later dismissed
thanks for your contribution. Could you check the test which you wrote? To run it locally you can use this command `yarn test:e2e:ganache:ws:chrome`

2022-10-27 13:00 UTC, Muhammad-Altabba requested changes
Looks great to me.
However, regarding the pipeline that fails sometimes. I think I detected the issue and I have a good suggestion. I run the test locally after applying the suggestion and they pass. Could you, please, accept the suggestion in order for the tests to run in the GitHub Actions pipeline?

2022-10-27 13:00 UTC, Muhammad-Altabba commented on packages/web3-eth-contract/test/integration/contract_events.test.ts
> +						);
There is a need to wait for every transaction, before firing the next one, to prevent a possible nonce duplication.
```suggestion
						for (const eventValue of eventValues) {
							// Wait for every transaction, before firing the next one, to prevent a possible nonce duplication.
							// eslint-disable-next-line no-await-in-loop
							await contractDeployed.methods
								.firesMultiValueEvent('Event Value', eventValue, false)
								.send(sendOptions);
						}

```

2022-11-01 02:26 UTC, alexmylonas commented on packages/web3-eth-contract/test/integration/contract_events.test.ts
> +						);
Yeap that did it, thank you!

2022-11-01 10:45 UTC, Muhammad-Altabba approved these changes

2022-11-03 15:38 UTC, luu-alex approved these changes

2022-11-03 16:30 UTC, Muhammad-Altabba commented
Dear @alexmylonas you need to get all previous commits signed and pushed again.

![image](https://user-images.githubusercontent.com/24407834/199778639-40d1ce75-3131-4b62-841a-b9555e97acb6.png)

2022-11-07 05:47 UTC, alexmylonas commented
Hey @Muhammad-Altabba. Rebased and signed all the commits! Let me know if there is anything more needed from my side.

2022-11-07 18:50 UTC, merged