eth.getBlock with hydrated = true returning empty transaction objects
ethereum/web3.js pull request #5556
Opened 2022-10-24 08:17 UTC by nikoulai

## Description

2022-10-25 10:21 UTC, jdevcs requested changes
In existing integration test , there should be additional check of transactions list present in case of hydrated true. or we can add a new test for querying a block with txs on some existing testnet.

2022-10-29 20:50 UTC, luu-alex approved these changes

2022-10-31 20:13 UTC, avkos approved these changes

2022-11-01 09:05 UTC, jdevcs approved these changes

2022-11-01 09:05 UTC, merged