5298/review docs
ethereum/web3.js pull request #5573
Opened 2022-10-27 19:23 UTC by luu-alex

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

2022-10-28 04:59 UTC, luu-alex commented
https://github.com/web3/web3.js/issues/5298#issuecomment-1202317959
 - guide link in footer is already removed
 - The docusuarus tutorial button has already been removed, so we can add a tutorials button when we have the tutorials section made.

2022-10-31 20:07 UTC, avkos approved these changes

2022-11-01 09:17 UTC, jdevcs requested changes

2022-11-01 09:17 UTC, jdevcs commented on docs/docs/guides/web3_migration_guide/personal_migration_guide.md
> +In 4.x, the method `extend` is deprecated in 4.x.
```suggestion
The method `extend` is deprecated in 4.x.
```

2022-11-01 09:17 UTC, jdevcs commented on docs/docs/guides/web3_migration_guide/personal_migration_guide.md
> +It will not have:
```suggestion
Web3.js 4.x will not have:
```

2022-11-01 09:36 UTC, jdevcs commented on docs/docs/guides/web3_tree_shaking_support_guide/index.md
The label of tree shaking guide should be "Web3 tree shaking guide" instead of `Web3.tree.shaking`

2022-11-01 09:37 UTC, jdevcs commented on docs/docs/guides/web3_tree_shaking_support_guide/index.md
in `sidebar_label: Web3.tree.shaking`

2022-11-01 09:39 UTC, jdevcs reviewed
https://github.com/web3/web3.js/pull/5558 PR was merged but Plugin guide is not appearing in this branch, could you rebase your branch?

2022-11-01 09:42 UTC, jdevcs requested changes

2022-11-01 09:42 UTC, jdevcs commented on docs/docs/guides/web3_migration_guide/accounts_migration_guide.md
>  ## Breaking changes
```suggestion
## Breaking Changes
```

2022-11-01 09:42 UTC, jdevcs commented on docs/docs/guides/web3_migration_guide/contracts_migration_guide.md
>  ### Breaking Changes
```suggestion
## Breaking Changes
```

2022-11-01 09:42 UTC, jdevcs commented
Thanks Alex, lgtm, just need some minor changes.

2022-11-01 14:46 UTC, nikoulai approved these changes

2022-11-04 14:57 UTC, jdevcs approved these changes

2022-11-05 02:14 UTC, merged