Add empty job
ethereum/web3.js pull request #5932
Opened 2023-03-16 14:49 UTC by nikoulai

## Description

closes #5584

2023-03-16 21:21 UTC, avkos requested changes

2023-03-16 21:21 UTC, avkos commented on README.md
> +test
remove unnecessary `test` here, please

2023-03-17 09:22 UTC, jdevcs approved these changes

2023-03-17 16:45 UTC, luu-alex approved these changes

2023-03-20 14:34 UTC, avkos approved these changes

2023-03-20 15:02 UTC, merged