Add types for user input in send/call
ethereum/web3.js pull request #5960
Opened 2023-03-27 14:21 UTC by nikoulai

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

2023-03-28 04:36 UTC, spacesailor24 requested changes
I don't think `InputNonPayableCallOptions` and `InputNonPayableTxOptions` are needed. I think the existing types `NonPayableCallOptions` and `NonPayableTxOptions` need to have the aforementioned properties removed

`1.x`'s `Contract.methods.method.call` allowed for the options:

![image](https://user-images.githubusercontent.com/20375610/228128328-26fe6748-242f-40b2-8bac-b20461d2474a.png)

`Contract.methods.method.send` allowed for:

![image](https://user-images.githubusercontent.com/20375610/228128483-f5c6c0fd-28db-487f-a317-3fed5017df01.png)

`estimateGas`:

![image](https://user-images.githubusercontent.com/20375610/228128532-3a71e287-9a43-4ba6-b74a-3dac5a55efae.png)

`createAccessList`:

![image](https://user-images.githubusercontent.com/20375610/228128566-f27f02fd-0e59-4356-b888-58adbdd0e427.png)

And `deploy`:

![image](https://user-images.githubusercontent.com/20375610/228128714-7def1074-fa6d-4154-8928-753c34dc2491.png)

I don't think the types `NonPayableCallOptions` and `NonPayableTxOptions` can be used for all these calls. I think we should update the types for each of these methods to match `1.x` with the addition of the fields: `maxPriorityFeePerGas`, `maxFeePerGas`, and `type`

2023-04-06 21:50 UTC, luu-alex approved these changes

2023-04-07 01:53 UTC, Muhammad-Altabba commented on packages/web3-eth-contract/src/contract.ts
> -		input?: HexString;
The documentation has to be updated for this :smile:. 
I found a use in the documentation here: https://github.com/web3/web3.js/blob/b88f2e8ac40b5718a8dbf8ac6701155442ce1bba/docs/docs/guides/sign_and_send_tx/local_wallet.md#L65-L66 and there possibly more.

2023-04-07 02:02 UTC, Muhammad-Altabba reviewed
Good job!

Could you please check for the case when the transaction for deploying a contract is signed (and the `input` is used when the transaction signed), and then the signed transaction is sent?

2023-04-11 12:55 UTC, jdevcs commented on packages/web3-eth-contract/src/types.ts
> -	input?: HexString;
Its diff from RC.0 so mention in changelog.

2023-04-11 12:56 UTC, jdevcs approved these changes
Approved, just changelog updates required.

2023-04-11 16:03 UTC, avkos approved these changes

2023-04-20 17:16 UTC, spacesailor24 requested changes

2023-04-20 17:16 UTC, Spacesai1or commented on docs/docs/guides/sign_and_send_tx/local_wallet.md
> +			data: ContractBytecode,
We renamed `data` to `input` in #5915, but we need to support both for backwards compatibility. Our docs should use `input` and our code should try to use `input` first, then try `data` if `input` was `undefined`

2023-04-20 17:16 UTC, Spacesai1or commented on packages/web3-eth-contract/src/contract.ts
> -
What's the reasoning behind removing this?

2023-04-20 17:16 UTC, spacesailor24 commented on packages/web3-eth-contract/src/types.ts
> +		tx?: Omit<NonPayableCallOptions, 'nonce'>,
It looks like `nonce` is allowed for `call`
<img width="412" alt="image" src="https://user-images.githubusercontent.com/20375610/233437711-dcc005ff-cb30-4ac2-8bba-bdcaa1b43381.png">

2023-04-20 17:16 UTC, spacesailor24 commented on packages/web3-eth-contract/src/types.ts
> +		options?: Omit<NonPayableCallOptions, 'nonce'>,
Looks like `nonce` is allowed for `estimateGas`
<img width="410" alt="image" src="https://user-images.githubusercontent.com/20375610/233437916-767633de-3c6d-4a13-a45e-78f0ba4abb92.png">

2023-04-20 17:16 UTC, spacesailor24 commented on packages/web3-eth-contract/src/types.ts
> +		tx?: Omit<NonPayableCallOptions, 'nonce' | 'type'>,
`nonce` and `type` allowed for `createAccessList`
<img width="401" alt="image" src="https://user-images.githubusercontent.com/20375610/233438214-3fc98c77-ec2d-41c4-880a-3d98a0ae46c9.png">

2023-04-20 17:16 UTC, spacesailor24 commented on packages/web3-eth-contract/src/types.ts
> +		tx?: Omit<NonPayableCallOptions, 'nonce'>,
These screenshots are coming from the [JSON RPC spec](https://ethereum.github.io/execution-apis/api-documentation/)

2023-04-20 18:33 UTC, nikoulai commented on packages/web3-eth-contract/src/contract.ts
> -
It's `PayableTxOptions` which extends `PayableCallOptions`/ `NonPayableCallOptions`, in which `to` field is removed in this PR.

2023-04-20 19:57 UTC, spacesailor24 commented on packages/web3-eth-contract/src/types.ts
> +		tx?: Omit<PayableCallOptions, 'nonce'>,
This omission should be removed as well, no? Same for `estimateGas` and `createAccessList` below

2023-04-20 19:57 UTC, spacesailor24 commented on packages/web3-eth-contract/test/unit/contract.test.ts
> +					data: GreeterBytecode,
```suggestion
					input: GreeterBytecode,
```

Since `input` is the correct term

2023-04-20 19:57 UTC, spacesailor24 commented on packages/web3-eth-contract/test/unit/contract.test.ts
> +					data: GreeterBytecode,
```suggestion
					input: GreeterBytecode,
```
Since `input` is the correct term

2023-04-20 19:58 UTC, spacesailor24 commented on docs/docs/guides/sign_and_send_tx/wallet_of_eth_node.md
> +			data: ContractBytecode,
```suggestion
			input: ContractBytecode,
```
Since `input` is the correct term

2023-04-20 19:59 UTC, Spacesai1or commented on packages/web3-eth-contract/src/contract.ts
> +	 *   input: '0x12345...', //data keyword can be used, too. But if input is used, data will be ignored.
```suggestion
	 *   input: '0x12345...', // data keyword can be used, too. If input is used, data will be ignored.
```

2023-04-24 08:05 UTC, Muhammad-Altabba reviewed
Could we have a test that verifies that the initially reported issue is fixed?
Thanks,

2023-04-24 08:05 UTC, Muhammad-Altabba commented on packages/web3-eth-contract/test/fixtures/schemaIdTest.ts
Where is this file being used?

2023-04-24 13:33 UTC, nikoulai commented on packages/web3-eth-contract/test/fixtures/schemaIdTest.ts
removed, thanks

2023-04-25 00:39 UTC, spacesailor24 approved these changes

2023-04-25 07:28 UTC, merged