Nikos/5939/eip1193 provider callback types
ethereum/web3.js pull request #5971
Opened 2023-03-29 13:58 UTC by nikoulai

## Description
 fixes events' callback types for eip1193 providers
 closes #5939 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

2023-03-30 08:45 UTC, BeroBurny requested changes

2023-03-30 08:45 UTC, BeroBurny commented on packages/web3-types/src/web3_base_provider.ts
> +		callback: Web3Eip1193ProviderEventCallback<{
seems that types are still wrong, if you check the [appendix of specification](https://eips.ethereum.org/EIPS/eip-1193#appendix-i-consumer-facing-api-documentation) you can observe different type

2023-03-30 08:48 UTC, BeroBurny commented on packages/web3-types/src/web3_base_provider.ts
> +		callback: Web3Eip1193ProviderEventCallback<{
maybe the wallet connect example can help visualize the issue
https://docs.walletconnect.com/1.0/quick-start/dapps/web3-provider#events-eip-1193

2023-04-03 23:26 UTC, Muhammad-Altabba commented on packages/web3-types/src/web3_api_types.ts
> +	message: string;
The Error interface provided by TypeScript already contains a `message` (and also a `name`) 
```suggestion
```

Here is the definision of the Error interface:
```ts
interface Error {
    name: string;
    message: string;
    stack?: string;
}
```

2023-04-04 03:03 UTC, Muhammad-Altabba commented on packages/web3-types/src/web3_base_provider.ts
>  	): void;
I think `removeListener` and `once` should have the same type restrictions as `on`.

2023-04-04 03:23 UTC, Muhammad-Altabba commented on packages/web3-utils/src/socket_provider.ts
>  	}
I am thinking that having only one implementation for `on` will not force the eact type restrictions we have at `Ẁeb3BaseProvider`. What do you think about having here something like this?:

```suggestion
	public abstract on(
		type: 'disconnect',
		listener: Web3Eip1193ProviderEventCallback<ProviderRpcError>,
	): void {
		this._eventEmitter.on(type, listener);
	}
	public abstract on<T = JsonRpcResult>(
		type: 'message' | string,
		listener: Web3Eip1193ProviderEventCallback<ProviderMessage> | Web3ProviderEventCallback<T>,
	): void {
		this._eventEmitter.on(type, listener);
	}
	public abstract on(
		type: 'connect',
		listener: Web3Eip1193ProviderEventCallback<ProviderConnectInfo>,
	): void {
		this._eventEmitter.on(type, listener);
	}
	public abstract on(
		type: 'chainChanged',
		listener: Web3Eip1193ProviderEventCallback<string>,
	): void {
		this._eventEmitter.on(type, listener);
	}
	public abstract on(
		type: 'accountsChanged',
		listener: Web3Eip1193ProviderEventCallback<string[]>,
	): void {
		this._eventEmitter.on(type, listener);
	}
	public abstract removeListener(
		type: string,
		listener: Web3Eip1193ProviderEventCallback<any> | Web3ProviderEventCallback,
	): void {
		this._eventEmitter.on(type, listener);
	}
```

And also doing the same for `once` and `removeListener`?

2023-04-06 16:33 UTC, avkos approved these changes

2023-04-11 02:25 UTC, Muhammad-Altabba commented on packages/web3-utils/src/socket_provider.ts
>  	}
It has been applied on `once` but not on `removeListener`. Is there a specific reason? Or was it just missed by a chance?

2023-04-11 11:41 UTC, Muhammad-Altabba approved these changes
LGTM.

However, there is tiny stuff. If you can address them, before merging.

2023-04-11 11:41 UTC, Muhammad-Altabba commented on packages/web3-utils/src/web3_eip1193_provider.ts
> +	// todo this must be ProvideRpcError with a message too
Could you please create an issue for this?

2023-04-11 11:41 UTC, Muhammad-Altabba commented on packages/web3-core/src/web3_subscriptions.ts
> +	Web3ProviderEventCallback,
I think this is not needed
```suggestion
```

2023-04-11 11:41 UTC, Muhammad-Altabba commented on packages/web3-core/src/web3_subscriptions.ts
> +			messageListener as Web3ProviderEventCallback<Log>,
I think the casting is not needed
```suggestion
		(this._requestManager.provider as Web3BaseProvider).on<Log>('message', messageListener);
```

2023-04-11 12:43 UTC, nikoulai commented on packages/web3-utils/src/web3_eip1193_provider.ts
> +	// todo this must be ProvideRpcError with a message too
https://github.com/web3/web3.js/issues/6003

2023-04-11 13:12 UTC, jdevcs commented on packages/web3-utils/src/socket_provider.ts
> +		listener: Web3Eip1193ProviderEventCallback<any> | Web3ProviderEventCallback<T>,
```suggestion
		listener: Web3Eip1193ProviderEventCallback<unknown> | Web3ProviderEventCallback<T>,
```
?

2023-04-11 13:13 UTC, jdevcs commented on packages/web3-utils/src/socket_provider.ts
> +		type: 'message' | string,
type: 'message' | string,
I think it should be only 'message', or is there reason of allowing it string as well?

2023-04-11 13:14 UTC, jdevcs commented on packages/web3-utils/src/socket_provider.ts
> +		listener: Web3Eip1193ProviderEventCallback<any> | Web3ProviderEventCallback<T>,
```suggestion
		listener: Web3Eip1193ProviderEventCallback<unknown> | Web3ProviderEventCallback<T>,
```
`any` should be avoided where possible in our lib.

2023-04-11 13:15 UTC, jdevcs commented on packages/web3-utils/src/socket_provider.ts
> +		listener: Web3Eip1193ProviderEventCallback<any> | Web3ProviderEventCallback<T>,
+ similar change proposed for other parts of code in this PR

2023-04-11 13:16 UTC, jdevcs reviewed
lgtm, except few changes required. ( also update change log ) Thanks @nikoulai

2023-04-20 18:19 UTC, merged