Specify SignTransaction's argument types
ethereum/web3.js pull request #5993
Opened 2023-04-05 23:11 UTC by Muhammad-Altabba

## Description

Fixes #5892

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

2023-04-10 15:36 UTC, avkos requested changes
Please, add information to changelog.md files

2023-04-10 18:07 UTC, nikoulai commented
Except for Oleksii's comment LGTM

2023-04-10 18:08 UTC, nikoulai approved these changes

2023-04-11 08:12 UTC, jdevcs requested changes

2023-04-11 08:12 UTC, jdevcs commented on packages/web3-eth-contract/CHANGELOG.md
> +-   The types `ContractAbiWithSignature`, `EventLog`, `ContractEventOptions`, `ContractOptions`, `ContractInitOptions` and `PayableCallOptions` moved to `web3-types`. (#5993)
Most of these types are used in contracts package only and not in other packages, except ( `ContractInitOptions` and `PayableCallOptions` ?). so only place shared types in web3-types package. 

Reason: non-shared code will blot other packages as web3-types is included in most of other packages.

2023-04-11 08:38 UTC, jdevcs commented
This PR lgtm, except few changes required. Thanks @Muhammad-Altabba

2023-04-11 17:06 UTC, jdevcs commented
Some of tests in CI are not passing and there are conflicting files. Could you fix these. Many thanks

2023-04-11 17:35 UTC, avkos approved these changes

2023-04-13 09:21 UTC, jdevcs approved these changes

2023-04-13 12:52 UTC, merged

2023-04-27 15:55 UTC, Hasinafidahussain commented
#6050