Fix error: "n.data.substring is not a function"
ethereum/web3.js pull request #6000
Opened 2023-04-10 12:30 UTC by Muhammad-Altabba

## Description

Fixes #5999 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

2023-04-10 15:26 UTC, avkos requested changes
Coverage decreased. It will be great to have unit test which cover these changes

2023-04-10 23:02 UTC, Muhammad-Altabba commented
> Coverage decreased. It will be great to have unit test which cover these changes

As a continuation of our chat: 

> The fixed issue is not presented when dealing with the local provider. And because of that the tests are passing and the issue is not detectable with our tests. But it exists when using Infura as it seems to have a slightly different data structure. And I tested this change on my local machine when connecting to Infura and it works well after the code modification.

So because we do not have a test setup with Infura and because this is not a case that can be produced with a local provider. And because it does not introduce any breaking changes (as it use `||` to get the object). I think it is fair enough to depend on a local test. Since doing a unit test (and not an integration test) for this seems to be meaningless. Or do have other thoughts?

Thanks,

2023-04-10 23:04 UTC, avkos approved these changes

2023-04-11 07:42 UTC, nikoulai approved these changes

2023-04-11 11:45 UTC, merged