6075 - update return format
ethereum/web3.js pull request #6083
Opened 2023-05-11 17:15 UTC by luu-alex

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

2023-05-11 20:09 UTC, avkos approved these changes

2023-05-12 09:37 UTC, nikoulai approved these changes

2023-05-12 14:20 UTC, mpetrunic requested changes
This addresses only smaller bug inside the issue.
Major one is that response on https://github.com/web3/web3.js/blob/4.x/packages/web3-eth/src/rpc_method_wrappers.ts#L884
is not formatted to string/uint8array but rather raw signature object is returned and propagated

2023-05-16 08:21 UTC, mpetrunic approved these changes

2023-05-16 10:38 UTC, jdevcs approved these changes

2023-05-16 13:55 UTC, merged