fix!: remove non read-only ens methods
ethereum/web3.js pull request #6084
Opened 2023-05-12 14:22 UTC by mpetrunic

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

2023-05-15 17:01 UTC, avkos requested changes
what issue is it fixed? if we do not have it will be better to create one.
And also, It reduced coverage. so it will be great to add some unit tests.

2023-05-19 13:05 UTC, jdevcs commented on packages/web3-eth-ens/src/registry.ts
> -	public setOwner(
As these are breaking changes so if you have time this should be mentioned in same PR in **migration guide** ? or we can add in some other PR?

2023-05-19 13:25 UTC, jdevcs approved these changes
some of tests in CI are not passing.

2023-05-19 14:00 UTC, mpetrunic commented
> some of tests in CI are not passing.

Can somebody else spin them locally? For me they are passing locally :/

2023-05-25 02:50 UTC, luu-alex approved these changes

2023-05-25 21:17 UTC, avkos approved these changes

2023-05-29 18:09 UTC, luu-alex approved these changes

2023-05-30 09:28 UTC, merged