fix estimateGas to accept hex data without 0x prefix
ethereum/web3.js pull request #6103
Opened 2023-05-18 12:34 UTC by nikoulai

## Description

closes #6088

2023-05-18 20:50 UTC, avkos requested changes
Could you please add the unit test to increase coverage?

2023-05-19 12:51 UTC, jdevcs commented
also some tests needs to be fixed
```
web3-eth-contract:   1 failing
web3-eth-contract:   1) contract
web3-eth-contract:        defaults
web3-eth-contract:          should use "defaultAccount" on "instance" level instead of "from":
web3-eth-contract:       AssertionError: expected 142780n to equal 'Any BigInt'
```

2023-05-22 09:42 UTC, djrann13 approved these changes

2023-05-22 14:29 UTC, jdevcs approved these changes

2023-05-22 14:36 UTC, avkos approved these changes

2023-05-22 16:40 UTC, merged