docs(local wallet): Property 'address' does not exist on type 'Wallet…
ethereum/web3.js pull request #6396
Opened 2023-08-31 07:18 UTC by Jogiter

…<Web3BaseWalletAccount>'

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

2023-08-31 12:46 UTC, jdevcs approved these changes

2023-08-31 12:46 UTC, jdevcs commented
@Jogiter Thanks for contribution.

2023-08-31 13:15 UTC, Muhammad-Altabba requested changes
I think we need to come up with a better suggestion for accessing the wallet. I will discuss this with the team and let you know.

2023-09-01 19:16 UTC, avkos approved these changes

2023-09-04 16:29 UTC, Muhammad-Altabba approved these changes
Many thanks for your contribution.
We can merge your MR and I added some [discussion points](https://github.com/web3/web3.js/issues/6397#issuecomment-1705527586) to your related issue and reopened it to keep tracking...

2023-09-07 17:33 UTC, merged