waitForTransactionReceipt fix
ethereum/web3.js pull request #6464
Opened 2023-09-27 17:52 UTC by jdevcs

## Description

https://github.com/web3/web3.js/issues/6328

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

2023-09-27 17:55 UTC, jdevcs commented
https://github.com/web3/web3.js/issues/6447 will also be fixed, 
For terminating receipt looking logic in less time, just set `web3.transactionPollingTimeout` to some lower value if you want lower thn [predefined](https://github.com/web3/web3.js/blob/b8fa7124d1d1e4c9c16b60ad2ce58559f72efd27/packages/web3-core/src/web3_config.ts#L76).

2023-09-27 17:56 UTC, jdevcs commented on packages/web3-utils/src/promise_helpers.ts
> +export async function pollTillDefined<T>(
keeping `pollTillDefined` so we dnt break API as its exported function from utils.

2023-10-02 16:46 UTC, luu-alex commented on packages/web3-utils/test/unit/promise_helpers.test.ts
> +
should have a testcase to manually `clearInterval` successfully

2023-10-03 15:26 UTC, avkos requested changes
Coverage decreased. Will be great to fix it

2023-10-04 17:32 UTC, jdevcs commented on packages/web3-utils/test/unit/promise_helpers.test.ts
> +
added

2023-10-04 20:32 UTC, avkos approved these changes

2023-10-05 02:20 UTC, luu-alex approved these changes

2023-10-05 14:07 UTC, merged