Proposal: Expose plugin functionality to plugins so it's easier to discover what plugins could do
ethereum/web3.js pull request #6538
Opened 2023-10-23 12:08 UTC by mpetrunic

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

2023-10-24 14:23 UTC, avkos approved these changes

2023-10-24 15:06 UTC, avkos requested changes
Could you please also fix tests
`packages/web3/test/integration/web3-plugin-add-tx.test.ts`
and
`packages/web3-eth-accounts/test/unit/tx/registerNewTx.test.ts`
to use this new method `registerNewTransactionType`

2023-10-30 09:31 UTC, jdevcs approved these changes

2023-11-07 14:22 UTC, avkos approved these changes

2023-11-13 18:16 UTC, Muhammad-Altabba approved these changes
Thanks for your contribution.
Just a small comment I think was missed.

2023-11-13 18:16 UTC, Muhammad-Altabba commented on packages/web3-core/src/web3_context.ts
This was provided early but I think got deleted by mistake, right?

```suggestion

/**
 * Extend this class when creating a plugin that either doesn't require {@link EthExecutionAPI},
 * or interacts with a RPC node that doesn't fully implement {@link EthExecutionAPI}.
 *
 * To add type support for RPC methods to the {@link Web3RequestManager},
 * define a {@link Web3APISpec} and pass it as a generic to Web3PluginBase like so:
 *
 * @example
 * ```ts
 * type CustomRpcApi = {
 *	custom_rpc_method: () => string;
 *	custom_rpc_method_with_parameters: (parameter1: string, parameter2: number) => string;
 * };
 *
 * class CustomPlugin extends Web3PluginBase<CustomRpcApi> {...}
 * ```
 */
```

2023-11-14 13:45 UTC, luu-alex approved these changes

2023-11-23 16:58 UTC, merged