doc: fix spelling and grammar for provider docs
ethereum/web3.js pull request #6572
Opened 2023-11-04 03:43 UTC by dkurukula

## Description

Fix a few minor spelling and grammar mistakes.

## Type of change

Documentation changes only.

2023-11-06 09:42 UTC, jdevcs approved these changes

2023-11-06 22:01 UTC, avkos approved these changes

2023-11-07 11:25 UTC, jdevcs commented
@dkurukula there are some merge conflicts, can you fix it, I'll merge this PR after that. Thanks

2023-11-09 09:07 UTC, jdevcs requested changes

2023-11-09 09:07 UTC, jdevcs commented on docs/docs/guides/web3_providers_guide/examples.md
> -					console.log('Accounts requested from MetaMask RPC: ', accounts);
why this is deleted?

2023-11-10 08:35 UTC, jdevcs approved these changes

2023-11-10 09:08 UTC, merged