Fix and error when trying to get past events by calling `contract.getPastEvents` or `contract.events.allEvents()` if there is no matching events.
ethereum/web3.js pull request #6647
Opened 2023-12-07 14:58 UTC by Muhammad-Altabba

## Description

Fixes #6644

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

2023-12-07 15:36 UTC, avkos requested changes

2023-12-07 15:36 UTC, avkos commented on packages/web3-eth-contract/CHANGELOG.md
> +-	Fix and error that happem when trying to get past events by calling `contract.getPastEvents` or `contract.events.allEvents()`, if there is no matching events. (#6647)
typo `happem`

2023-12-07 15:36 UTC, avkos commented on packages/web3-eth-contract/src/contract.ts
>  						logs.forEach(log => sub.emit('data', log as EventLog));
I think this line should be deleted

2023-12-08 16:43 UTC, avkos approved these changes

2023-12-11 12:55 UTC, jdevcs reviewed
lgtm, need following to pass:
Failing after 1s — 80.00% of diff hit (target 90.81%)

2023-12-12 12:29 UTC, jdevcs approved these changes

2023-12-12 13:27 UTC, merged