chore: fix some comments
ethereum/web3.js pull request #6884
Opened 2024-03-12 03:55 UTC by pavedroad

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](https://github.com/web3/web3.js/blob/4.x/.github/CONTRIBUTING.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

2024-03-12 11:47 UTC, jdevcs approved these changes

2024-03-12 11:48 UTC, jdevcs requested changes
pls also update test snapshots, so following tests are passing https://github.com/web3/web3.js/actions/runs/8243330205/job/22554409042?pr=6884#step:4:305

2024-03-12 11:49 UTC, jdevcs commented
@pavedroad

2024-03-12 12:07 UTC, pavedroad commented
> pls also update test snapshots, so following tests are passing https://github.com/web3/web3.js/actions/runs/8243330205/job/22554409042?pr=6884#step:4:305

Thanks!  

Modified.please review again.

2024-03-12 12:54 UTC, jdevcs commented
> > pls also update test snapshots, so following tests are passing https://github.com/web3/web3.js/actions/runs/8243330205/job/22554409042?pr=6884#step:4:305
> 
> Thanks!
> 
> Modified.please review again.

re invoked CI, thanks

2024-03-14 13:52 UTC, avkos approved these changes

2024-04-04 12:11 UTC, closed without merging

2024-04-04 12:11 UTC, jdevcs commented
this will be done by our team member in diff PR/issue

2024-04-04 12:35 UTC, jisen210 commented on packages/web3-errors/test/unit/__snapshots__/rpc-errors.test.ts.snap
> -  "message": "An Rpc error has occured with a code of 99999",
Occurred

2024-04-24 07:49 UTC, pavedroad commented
Thanks!