Plugin guide 6840 draft
ethereum/web3.js pull request #6941
Opened 2024-03-26 22:08 UTC by SantiagoDevRel

2024-04-22 12:59 UTC, jdevcs commented on docs/docs/guides/web3_plugin_guide/index.md
> +### Register plugin (External - Final user)
This section is overlapping with '## Use a plugin' so it should be removed.

2024-04-22 13:02 UTC, jdevcs commented on docs/docs/guides/web3_plugin_guide/index.md
> +There are 2 ways to initialize a provider when you are using a plugin, the [first one](#set-a-provider-within-the-plugin) is within the plugin (internally using the `this` object and `setProvider()`
I think this section should also be removed as its overlapping with **Set a provider within the plugin (web3Context)**, and ideally plugin dev shouldnt worry about modifying provider unless there is any special use case and for that you added section : **Set a provider within the plugin (web3Context)**

2024-04-22 13:04 UTC, jdevcs commented on docs/docs/guides/web3_plugin_guide/index.md
> +  }
these setprovider will only work for rest of lib if its context is applied via link override like: 
https://github.com/ChainSafe/web3-plugin-chainstack/blob/fbe7b2376ca8623db3801b41f96e4f0fb3b8ef2d/src/chainstack-plugin.ts#L43

and provider is set for parent context like:
https://github.com/ChainSafe/web3-plugin-chainstack/blob/fbe7b2376ca8623db3801b41f96e4f0fb3b8ef2d/src/chainstack-plugin.ts#L87

2024-04-22 13:10 UTC, jdevcs commented
This PR lgtm , only few changes suggested.

2024-04-22 17:36 UTC, avkos requested changes

2024-04-22 17:36 UTC, avkos commented on docs/docs/guides/web3_plugin_guide/index.md
> +There are 2 ways to initialize a provider when you are using a plugin, the [first one](#set-a-provider-within-the-plugin) is within the plugin (internally using the `this` object and `setProvider()`
I think, setting a provider inside a plugin is a bad practice. Users of the plugin should decide what provider they want to use

2024-04-23 01:28 UTC, avkos approved these changes

2024-04-23 08:46 UTC, jdevcs approved these changes

2024-04-23 08:47 UTC, merged