web3 external provider - Quicknode
ethereum/web3.js pull request #7019
Opened 2024-04-30 16:07 UTC by jdevcs

## Description

#6976

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

2024-05-17 16:33 UTC, avkos requested changes

2024-05-17 16:33 UTC, avkos commented on packages/web3-providers/src/web3_provider_quicknode.ts
> +                break;
is it ok to have tokens here?

2024-05-17 17:02 UTC, luu-alex reviewed
Looks good, just some feedback.
Integration tests should be created before release of the package

2024-05-17 17:02 UTC, luu-alex commented on packages/web3-providers/package.json
> +	"version": "0.1.0",
if we start at 0.1.0 that would that be considered alpha

2024-05-21 10:40 UTC, jdevcs commented on packages/web3-providers/src/web3_provider_quicknode.ts
> +                break;
yes, these are public tokens

2024-05-21 10:41 UTC, jdevcs commented on packages/web3-providers/package.json
> +	"version": "0.1.0",
yes, 1.0.0 will be prod

2024-05-21 14:28 UTC, avkos approved these changes

2024-05-24 13:56 UTC, luu-alex commented
Failing testcases, otherwise it looks good

2024-05-27 11:58 UTC, merged