7203 - Alchemy rpc provider
ethereum/web3.js pull request #7296
Opened 2024-10-02 18:28 UTC by MRLab12

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](https://github.com/web3/web3.js/blob/4.x/.github/CONTRIBUTING.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

2024-10-07 09:25 UTC, jdevcs commented on packages/web3-rpc-providers/src/web3_provider_alchemy.ts
> +	}
```suggestion

```
As currently there is no custom logic for this provider. 429 status code is specific for QN provider

2024-10-07 09:28 UTC, jdevcs commented on packages/web3-rpc-providers/src/web3_provider_alchemy.ts
> +		switch (network) {
instead of switch use map as https://github.com/web3/web3.js/pull/7260/files#diff-b3d860d130c02e49ecd127d925384fe54f14e0b93c94aec96cf2965781c9efa8R37

2024-10-17 15:58 UTC, avkos requested changes

2024-10-17 15:58 UTC, avkos commented on packages/web3-rpc-providers/src/web3_provider_alchemy.ts
> +	};
It would be great to add all Alchemy platforms if they are compatible with web3js.

<img width="885" alt="image" src="https://github.com/user-attachments/assets/29623525-f25f-4ca9-a21e-36e0672317c0">

2024-10-17 15:58 UTC, avkos commented on packages/web3/test/integration/web3RPCProviders.test.ts
> +			it(`AlchemyProvider should work with ${transport} transport and ${network} network`, async () => {
After adding all platforms it will be a different array of networks. so it will be better to have separate const `networksAlchemy` and separate test `networksAlchemy.forEach`

2024-10-17 18:24 UTC, MRLab12 commented on packages/web3-rpc-providers/src/web3_provider_alchemy.ts
> +	};
Is this screenshot from web.js? Wondering if this is an accurate list of the chains to support with Alchemy.

2024-10-31 18:48 UTC, MRLab12 commented on packages/web3-rpc-providers/src/web3_provider_alchemy.ts
> +	};
@avkos Made some changes, not sure if all the chains I added are to be supported but lmk.

2024-11-05 10:59 UTC, Muhammad-Altabba approved these changes
Many thanks @MRLab12 for your contribution,
It seems great now. I think, once other team members approve, we can merge this MR.

2024-11-12 23:25 UTC, MRLab12 commented
I'm trying to run integration tests locally but having issues. Looking at the test errors here, most likely a missing Alchemy key is the issue. Can someone point me to how this should be set up?

2024-11-25 14:48 UTC, jdevcs commented
> I'm trying to run integration tests locally but having issues. Looking at the test errors here, most likely a missing Alchemy key is the issue. Can someone point me to how this should be set up?

For your local testing I'll suggest to use your personal key, and for web3.js one of our team member will add web3.js specific alchemy key.

2024-11-25 15:02 UTC, MRLab12 commented
> > I'm trying to run integration tests locally but having issues. Looking at the test errors here, most likely a missing Alchemy key is the issue. Can someone point me to how this should be set up?
> 
> For your local testing I'll suggest to use your personal key, and for web3.js one of our team member will add web3.js specific alchemy key.

Hey! Yup, I used my personal key to manually test the functionality using a script. For the tests I added, I thought these tests were going to be ignored for now. Since it looks like they are being used, we will most likely need to set up the key for the tests to work.

I'm going to try to get the tests I added to run locally, but when I last tried using `WEB3_SYSTEM_TEST_BACKEND=geth WEB3_SYSTEM_TEST_PROVIDER=ws://127.0.0.1:8545 yarn test:integration`, tests seem to work but it also generates some errors.  Maybe someone can help me out with running newly added tests locally without running all the test suites.

2025-01-21 10:38 UTC, jdevcs commented
Thank you for your PR. We appreciate your contributions to the Web3.js library.
As you may be aware, we are in the process of sunsetting Web3.js, and as such, we will not be merging any non-critical pull requests. 
Our focus during this transition will be on addressing critical issues to ensure a smooth migration for our users.
For further details regarding the sunsetting of Web3.js, please refer to the official announcement here: [Web3.js Sunset Announcement](https://blog.chainsafe.io/web3-js-sunset/)

2025-01-21 10:38 UTC, closed without merging