Adjusted fromWei
ethereum/web3.js pull request #7366
Opened 2024-10-30 22:28 UTC by TemirlanBasitov

## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](https://github.com/web3/web3.js/blob/4.x/.github/CONTRIBUTING.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

2024-10-31 14:10 UTC, avkos requested changes

2024-10-31 14:10 UTC, avkos commented on packages/web3-utils/src/converters.ts
> +		return fraction ? `0.${fraction}` : "0";
It will be great to add a unit test to cover this line. thanks

2024-10-31 15:59 UTC, danforbes commented on CHANGELOG.md
Are the changes to this file intentional?

2024-11-19 09:53 UTC, krzysu commented
The issue has been resolved with [this PR](https://github.com/web3/web3.js/pull/7387), making this one no longer relevant. Thank you, @TemirlanBasitov, for your effort and contribution—it’s greatly appreciated! 🙌

2024-11-19 09:53 UTC, closed without merging